package observability

import (
	"fmt"
	"os"
	"sort"
	"strings"
	"testing"
	"time"

	"github.com/prometheus/client_golang/prometheus"
	dto "github.com/prometheus/client_model/go"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// TestRenderLegacy_HeadersConsts locks the customer-API contract bytes.
// GREEN immediately and stays GREEN forever — any edit fails CI and forces
// an ADR amendment per CLAUDE.md "Public API contract — Metric names and
// span names are versioned. Deprecations require Sunset header overlap of
// one minor release minimum."
func TestRenderLegacy_HeadersConsts(t *testing.T) {
	require.Equal(t, "Fri, 31 Dec 2027 23:59:59 GMT", LegacySunset, "Sunset literal is locked customer-API contract; change requires ADR amendment")
	require.Equal(t, "true", LegacyDeprecation, "Deprecation literal locked per R-01 (deliberate RFC-9745 non-conformance for M1)")
	require.Equal(t, "text/plain; version=0.0.4; charset=utf-8", LegacyContentType, "Prometheus exposition v0.0.4 — locked")
}

// TestRenderLegacy_Snapshot is the TEST-03 golden-file lock. RED in Wave-0
// because (a) golden file does not exist and (b) RenderLegacy returns nil.
// Plan 05-02 generates the golden file and implements RenderLegacy; this
// test then turns GREEN and stays GREEN as the durable byte-level contract.
func TestRenderLegacy_Snapshot(t *testing.T) {
	te := NewTestEnv(t)
	// Plan 05-02 will populate te.Registry with deterministic source families
	// matching the legacy_snapshot.golden bytes. Wave-0 leaves the helper
	// a TODO; the golden file is generated by Plan 05-02.
	seedDeterministicLegacySources(t, te.Registry)

	fixedTime := time.Date(2026, 5, 4, 12, 0, 0, 0, time.UTC)
	got := RenderLegacy(te.Registry, fixedTime)

	want, err := os.ReadFile("legacy_snapshot.golden")
	if os.IsNotExist(err) {
		t.Fatalf("golden file pkg/observability/legacy_snapshot.golden missing — Plan 05-02 must generate it. Got bytes:\n%s", string(got))
	}
	require.NoError(t, err)
	require.Equal(t, string(want), string(got),
		"byte-mismatch against legacy_snapshot.golden — regenerate by running Plan 05-02 fixture generator after legitimate change")
}

// seedDeterministicLegacySources registers the source metric families on
// reg with deterministic fixed values. The choice of values is locked by
// pkg/observability/legacy_snapshot.golden — change a value here and the
// snapshot test goes RED, forcing a conscious regenerate via REGEN=1.
//
// Coverage rationale:
//   - http_requests_total has three samples across {method, path_template,
//     status_class} — tests sumAcrossLabels (total=12) and the
//     status_class==5xx branch of sumByMatchingLabel (total=2).
//   - embed_processed_total has three rows across result={success,
//     failure, cached} — tests both result-filter branches AND that
//     cached observations are not counted by either legacy mapping.
//   - storage nodes/edges + cypher_slow_query_threshold_seconds + uptime
//     are label-less GaugeFuncs (per Phase 4 catalog reality).
//   - cypher_slow_queries_total uses the no-label CounterVec shape (the
//     tenantLabels=false branch); multi-shape coverage is in
//     TestRenderLegacy_Reductions.
//   - build_info uses ConstLabels {version, commit, go_version, backend}
//     — the dropExtraLabels emit retains only {version, backend} per
//     mapping row 12.
func seedDeterministicLegacySources(t *testing.T, reg *prometheus.Registry) {
	t.Helper()

	// 1. uptime
	reg.MustRegister(prometheus.NewGaugeFunc(
		prometheus.GaugeOpts{Name: "nornicdb_process_uptime_seconds", Help: "Server uptime in seconds"},
		func() float64 { return 42 },
	))

	// 2-3. http requests (multi-label) — feeds requests_total + errors_total
	httpReq := prometheus.NewCounterVec(
		prometheus.CounterOpts{Name: "nornicdb_http_requests_total", Help: "Total HTTP requests"},
		[]string{"method", "path_template", "status_class"},
	)
	httpReq.WithLabelValues("GET", "/x", "2xx").Add(8)
	httpReq.WithLabelValues("POST", "/y", "2xx").Add(2)
	httpReq.WithLabelValues("GET", "/x", "5xx").Add(2)
	reg.MustRegister(httpReq)

	// 4. http in-flight (no labels)
	inflight := prometheus.NewGauge(prometheus.GaugeOpts{
		Name: "nornicdb_http_in_flight_requests",
		Help: "In-flight HTTP requests",
	})
	inflight.Set(3)
	reg.MustRegister(inflight)

	// 5-6. storage nodes/edges (label-less GaugeFunc per RESEARCH MAPPING-CORRECTION)
	reg.MustRegister(prometheus.NewGaugeFunc(
		prometheus.GaugeOpts{Name: "nornicdb_storage_nodes_total", Help: "Total nodes"},
		func() float64 { return 100 },
	))
	reg.MustRegister(prometheus.NewGaugeFunc(
		prometheus.GaugeOpts{Name: "nornicdb_storage_edges_total", Help: "Total edges"},
		func() float64 { return 200 },
	))

	// 7-8. embed processed (success / failure / cached)
	embed := prometheus.NewCounterVec(
		prometheus.CounterOpts{Name: "nornicdb_embed_processed_total", Help: "Total embeddings processed"},
		[]string{"provider", "model", "result", "mode"},
	)
	embed.WithLabelValues("local", "m", "success", "cpu").Add(50)
	embed.WithLabelValues("local", "m", "failure", "cpu").Add(5)
	embed.WithLabelValues("local", "m", "cached", "cpu").Add(99)
	reg.MustRegister(embed)

	// 9. embed worker
	worker := prometheus.NewGauge(prometheus.GaugeOpts{
		Name: "nornicdb_embed_worker_running",
		Help: "Worker running",
	})
	worker.Set(1)
	reg.MustRegister(worker)

	// 10. cypher slow queries (no labels — tenantLabels=false case)
	slow := prometheus.NewCounterVec(
		prometheus.CounterOpts{Name: "nornicdb_cypher_slow_queries_total", Help: "Total slow queries"},
		[]string{},
	)
	slow.WithLabelValues().Add(7)
	reg.MustRegister(slow)

	// 11. cypher slow_query_threshold_seconds
	reg.MustRegister(prometheus.NewGaugeFunc(
		prometheus.GaugeOpts{Name: "nornicdb_cypher_slow_query_threshold_seconds", Help: "Slow query threshold seconds"},
		func() float64 { return 1.0 },
	))

	// 12. build info (with ConstLabels; KeepLabels filters at emit time)
	reg.MustRegister(prometheus.NewGaugeFunc(
		prometheus.GaugeOpts{
			Name: "nornicdb_build_info",
			Help: "Build info",
			ConstLabels: prometheus.Labels{
				"version":    "1.0.0",
				"commit":     "abc1234",
				"go_version": "go1.26.0",
				"backend":    "badger",
			},
		},
		func() float64 { return 1 },
	))
}

// TestRenderLegacy_RegenerateGolden writes legacy_snapshot.golden from a
// fresh seedDeterministicLegacySources fixture. Gated behind REGEN=1 so
// CI cannot accidentally re-write the locked file.
//
// Operator workflow: when a Phase 4 catalog change legitimately alters
// the legacy translation output, run:
//
//	REGEN=1 go test ./pkg/observability/ -run TestRenderLegacy_RegenerateGolden -count=1
//
// then commit the new golden file alongside the catalog change + an ADR
// amendment recording the bytes diff.
func TestRenderLegacy_RegenerateGolden(t *testing.T) {
	if os.Getenv("REGEN") == "" {
		t.Skip("set REGEN=1 to regenerate legacy_snapshot.golden")
	}
	te := NewTestEnv(t)
	seedDeterministicLegacySources(t, te.Registry)
	got := RenderLegacy(te.Registry, time.Date(2026, 5, 4, 12, 0, 0, 0, time.UTC))
	require.NoError(t, os.WriteFile("legacy_snapshot.golden", got, 0o644))
	t.Logf("wrote legacy_snapshot.golden (%d bytes)", len(got))
}

// TestRenderLegacy_Mapping table-driven, one row per legacy metric name.
// Each row registers all 12 deterministic source families via the shared
// seedDeterministicLegacySources fixture and asserts the row's specific
// rendered value. The wantValue column is the canonical reduction
// outcome locked alongside the golden file.
func TestRenderLegacy_Mapping(t *testing.T) {
	cases := []struct {
		legacyName string
		setupReg   func(*testing.T, *prometheus.Registry)
		wantValue  float64
	}{
		{legacyName: "nornicdb_uptime_seconds", setupReg: seedDeterministicLegacySources, wantValue: 42},
		{legacyName: "nornicdb_requests_total", setupReg: seedDeterministicLegacySources, wantValue: 12},
		{legacyName: "nornicdb_errors_total", setupReg: seedDeterministicLegacySources, wantValue: 2},
		{legacyName: "nornicdb_active_requests", setupReg: seedDeterministicLegacySources, wantValue: 3},
		{legacyName: "nornicdb_nodes_total", setupReg: seedDeterministicLegacySources, wantValue: 100},
		{legacyName: "nornicdb_edges_total", setupReg: seedDeterministicLegacySources, wantValue: 200},
		{legacyName: "nornicdb_embeddings_processed", setupReg: seedDeterministicLegacySources, wantValue: 50},
		{legacyName: "nornicdb_embeddings_failed", setupReg: seedDeterministicLegacySources, wantValue: 5},
		{legacyName: "nornicdb_embedding_worker_running", setupReg: seedDeterministicLegacySources, wantValue: 1},
		{legacyName: "nornicdb_slow_queries_total", setupReg: seedDeterministicLegacySources, wantValue: 7},
		{legacyName: "nornicdb_slow_query_threshold_ms", setupReg: seedDeterministicLegacySources, wantValue: 1000},
		{legacyName: "nornicdb_info", setupReg: seedDeterministicLegacySources, wantValue: 1},
	}
	for _, tc := range cases {
		t.Run(tc.legacyName, func(t *testing.T) {
			te := NewTestEnv(t)
			if tc.setupReg != nil {
				tc.setupReg(t, te.Registry)
			}
			body := RenderLegacy(te.Registry, time.Date(2026, 5, 4, 12, 0, 0, 0, time.UTC))
			require.NotEmpty(t, body, "RenderLegacy returned empty bytes — Plan 05-02 must implement")
			value := parseLegacyValue(t, body, tc.legacyName)
			assert.Equal(t, tc.wantValue, value)
		})
	}
}

// parseLegacyValue scans the exposition text for a sample line matching
// legacyName (with optional ConstLabels for nornicdb_info) and returns the
// float64 value. Helper used by mapping + snapshot tests.
func parseLegacyValue(t *testing.T, body []byte, legacyName string) float64 {
	t.Helper()
	for _, line := range strings.Split(string(body), "\n") {
		if strings.HasPrefix(line, "#") || line == "" {
			continue
		}
		// Match either bare "name 42" or labeled "name{k="v"} 1"
		if !strings.HasPrefix(line, legacyName) {
			continue
		}
		parts := strings.Fields(line)
		if len(parts) < 2 {
			continue
		}
		// Use Sscanf to parse trailing float
		var v float64
		if _, err := fmt.Sscanf(parts[len(parts)-1], "%f", &v); err == nil {
			return v
		}
	}
	t.Fatalf("legacy metric %q not found in output:\n%s", legacyName, string(body))
	return 0
}

// gatherByName runs reg.Gather() and returns the family-by-name index used
// by reduction helpers. Test-local mirror of the byName build inside
// RenderLegacy.
func gatherByName(t *testing.T, reg *prometheus.Registry) map[string]*dto.MetricFamily {
	t.Helper()
	families, err := reg.Gather()
	require.NoError(t, err)
	out := map[string]*dto.MetricFamily{}
	for _, mf := range families {
		if mf == nil {
			continue
		}
		out[mf.GetName()] = mf
	}
	return out
}

// TestRenderLegacy_Reductions covers the four reduction helpers across
// edge cases — nil-family, single-sample, multi-sample, label-match,
// no-match, and ConstLabel-bearing rows. Plan 05-02 implements the
// positive-value paths.
func TestRenderLegacy_Reductions(t *testing.T) {
	t.Run("sumAcrossLabels_nil_family", func(t *testing.T) {
		byName := map[string]*dto.MetricFamily{}
		got := sumAcrossLabels(byName, legacyMapping{Sources: []string{"missing"}})
		assert.Equal(t, float64(0), got)
	})
	t.Run("sumByMatchingLabel_nil_family", func(t *testing.T) {
		byName := map[string]*dto.MetricFamily{}
		got := sumByMatchingLabel(byName, legacyMapping{Sources: []string{"missing"}})
		assert.Equal(t, float64(0), got)
	})
	t.Run("takeLatest_nil_family", func(t *testing.T) {
		byName := map[string]*dto.MetricFamily{}
		got := takeLatest(byName, legacyMapping{Sources: []string{"missing"}})
		assert.Equal(t, float64(0), got)
	})
	t.Run("dropExtraLabels_nil_family", func(t *testing.T) {
		byName := map[string]*dto.MetricFamily{}
		got := dropExtraLabels(byName, legacyMapping{Sources: []string{"missing"}})
		assert.Equal(t, float64(0), got)
	})

	t.Run("sumAcrossLabels_multi_sample", func(t *testing.T) {
		reg := prometheus.NewRegistry()
		vec := prometheus.NewCounterVec(
			prometheus.CounterOpts{Name: "x_total", Help: "x"},
			[]string{"method"},
		)
		vec.WithLabelValues("GET").Add(5)
		vec.WithLabelValues("POST").Add(10)
		vec.WithLabelValues("PUT").Add(20)
		reg.MustRegister(vec)
		byName := gatherByName(t, reg)
		got := sumAcrossLabels(byName, legacyMapping{Sources: []string{"x_total"}})
		assert.Equal(t, float64(35), got)
	})

	t.Run("sumByMatchingLabel_match", func(t *testing.T) {
		reg := prometheus.NewRegistry()
		vec := prometheus.NewCounterVec(
			prometheus.CounterOpts{Name: "y_total", Help: "y"},
			[]string{"method"},
		)
		vec.WithLabelValues("GET").Add(10)
		vec.WithLabelValues("POST").Add(99)
		reg.MustRegister(vec)
		byName := gatherByName(t, reg)
		got := sumByMatchingLabel(byName, legacyMapping{
			Sources:    []string{"y_total"},
			MatchLabel: "method",
			MatchValue: "GET",
		})
		assert.Equal(t, float64(10), got)
	})

	t.Run("sumByMatchingLabel_no_match", func(t *testing.T) {
		reg := prometheus.NewRegistry()
		vec := prometheus.NewCounterVec(
			prometheus.CounterOpts{Name: "z_total", Help: "z"},
			[]string{"method"},
		)
		vec.WithLabelValues("GET").Add(10)
		reg.MustRegister(vec)
		byName := gatherByName(t, reg)
		got := sumByMatchingLabel(byName, legacyMapping{
			Sources:    []string{"z_total"},
			MatchLabel: "method",
			MatchValue: "zzz",
		})
		assert.Equal(t, float64(0), got)
	})

	t.Run("takeLatest_single_sample", func(t *testing.T) {
		reg := prometheus.NewRegistry()
		reg.MustRegister(prometheus.NewGaugeFunc(
			prometheus.GaugeOpts{Name: "g_value", Help: "g"},
			func() float64 { return 42 },
		))
		byName := gatherByName(t, reg)
		got := takeLatest(byName, legacyMapping{Sources: []string{"g_value"}})
		assert.Equal(t, float64(42), got)
	})

	t.Run("takeLatest_empty_metric_slice", func(t *testing.T) {
		reg := prometheus.NewRegistry()
		vec := prometheus.NewCounterVec(
			prometheus.CounterOpts{Name: "empty_total", Help: "empty"},
			[]string{"label"},
		)
		// No WithLabelValues — Vec has zero observations.
		reg.MustRegister(vec)
		byName := gatherByName(t, reg)
		got := takeLatest(byName, legacyMapping{Sources: []string{"empty_total"}})
		assert.Equal(t, float64(0), got)
	})

	t.Run("dropExtraLabels_with_const_labels", func(t *testing.T) {
		reg := prometheus.NewRegistry()
		reg.MustRegister(prometheus.NewGaugeFunc(
			prometheus.GaugeOpts{
				Name:        "info_value",
				Help:        "info",
				ConstLabels: prometheus.Labels{"version": "1.0", "backend": "badger"},
			},
			func() float64 { return 1 },
		))
		byName := gatherByName(t, reg)
		got := dropExtraLabels(byName, legacyMapping{
			Sources:    []string{"info_value"},
			KeepLabels: []string{"version", "backend"},
		})
		assert.Equal(t, float64(1), got)
	})

	t.Run("metricValue_unknown_type", func(t *testing.T) {
		// A nil metric for any type returns 0. Use UNTYPED with nil Untyped.
		got := metricValue(dto.MetricType_HISTOGRAM, &dto.Metric{})
		assert.Equal(t, float64(0), got)
	})

	t.Run("labelMatches_empty_name", func(t *testing.T) {
		assert.False(t, labelMatches(nil, "", ""))
	})
}

// TestRenderLegacy_DeterministicOrdering enforces D-01d sort-by-LegacyName.
// RED in Wave-0 (RenderLegacy returns nil); Plan 05-02 GREEN.
func TestRenderLegacy_DeterministicOrdering(t *testing.T) {
	te := NewTestEnv(t)
	seedDeterministicLegacySources(t, te.Registry)
	body := RenderLegacy(te.Registry, time.Date(2026, 5, 4, 12, 0, 0, 0, time.UTC))
	require.NotEmpty(t, body)
	var names []string
	for _, line := range strings.Split(string(body), "\n") {
		if strings.HasPrefix(line, "# TYPE ") {
			parts := strings.Fields(line)
			if len(parts) >= 3 {
				names = append(names, parts[2])
			}
		}
	}
	require.NotEmpty(t, names)
	sorted := append([]string(nil), names...)
	sort.Strings(sorted)
	assert.Equal(t, sorted, names, "legacy metrics must be emitted sorted by name (D-01d)")
}
