package inference

import (
	"context"
	"testing"
	"time"

	"github.com/orneryd/nornicdb/pkg/storage"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

type trackingDecayEngine struct {
	*storage.MemoryEngine
	updated []storage.EdgeID
	deleted []storage.EdgeID
}

func (e *trackingDecayEngine) UpdateEdge(edge *storage.Edge) error {
	e.updated = append(e.updated, edge.ID)
	return e.MemoryEngine.UpdateEdge(edge)
}

func (e *trackingDecayEngine) DeleteEdge(id storage.EdgeID) error {
	e.deleted = append(e.deleted, id)
	return e.MemoryEngine.DeleteEdge(id)
}

func createDecayFixtureEdge(t *testing.T, engine storage.Engine, edge *storage.Edge) {
	t.Helper()
	err := engine.CreateEdge(edge)
	require.NoError(t, err)
}

func TestDefaultEdgeDecayConfigAndHelpers(t *testing.T) {
	cfg := DefaultEdgeDecayConfig()
	require.NotNil(t, cfg)
	assert.True(t, cfg.Enabled)
	assert.Equal(t, 0.95, cfg.DecayRate)
	assert.Equal(t, 0.3, cfg.MinConfidence)
	assert.Equal(t, 7*24*time.Hour, cfg.GracePeriod)
	assert.Equal(t, time.Hour, cfg.ScanInterval)
	assert.Equal(t, 1000, cfg.MaxEdgesPerScan)
	assert.True(t, cfg.OnlyAutoGenerated)
	assert.False(t, cfg.DryRun)

	engine := NewEdgeDecay(nil, storage.NewMemoryEngine())
	require.NotNil(t, engine)
	require.NotNil(t, engine.config)
	assert.NotNil(t, engine.reinforced)

	engine.ReinforceEdge("edge-1")
	assert.Contains(t, engine.reinforced, storage.EdgeID("edge-1"))
	assert.Equal(t, EdgeDecayStats{}, engine.GetStats())

	assert.Equal(t, 1.0, pow(0.5, 0))
	assert.InDelta(t, 0.25, pow(0.5, 2), 1e-9)
	assert.InDelta(t, 0.475, pow(0.5, 1.1), 1e-9)
}

func TestEdgeDecay_StartStopAndTriggerScan(t *testing.T) {
	store := &trackingDecayEngine{MemoryEngine: storage.NewMemoryEngine()}
	_, err := store.CreateNode(&storage.Node{ID: "nornic:n1"})
	require.NoError(t, err)
	_, err = store.CreateNode(&storage.Node{ID: "nornic:n2"})
	require.NoError(t, err)

	now := time.Now()
	old := now.Add(-24 * time.Hour)

	createDecayFixtureEdge(t, store, &storage.Edge{
		ID:            "nornic:decay-me",
		StartNode:     "nornic:n1",
		EndNode:       "nornic:n2",
		Type:          "RELATES_TO",
		Confidence:    0.9,
		AutoGenerated: true,
		CreatedAt:     old,
		UpdatedAt:     old,
	})
	createDecayFixtureEdge(t, store, &storage.Edge{
		ID:            "nornic:delete-me",
		StartNode:     "nornic:n1",
		EndNode:       "nornic:n2",
		Type:          "RELATES_TO",
		Confidence:    0.4,
		AutoGenerated: true,
		CreatedAt:     old,
		UpdatedAt:     old,
	})
	createDecayFixtureEdge(t, store, &storage.Edge{
		ID:            "nornic:manual-edge",
		StartNode:     "nornic:n1",
		EndNode:       "nornic:n2",
		Type:          "RELATES_TO",
		Confidence:    0.4,
		AutoGenerated: false,
		CreatedAt:     old,
		UpdatedAt:     old,
	})
	createDecayFixtureEdge(t, store, &storage.Edge{
		ID:            "nornic:reinforced-edge",
		StartNode:     "nornic:n1",
		EndNode:       "nornic:n2",
		Type:          "RELATES_TO",
		Confidence:    0.4,
		AutoGenerated: true,
		CreatedAt:     old,
		UpdatedAt:     old,
	})

	decay := NewEdgeDecay(&EdgeDecayConfig{
		Enabled:           true,
		DecayRate:         0.5,
		MinConfidence:     0.3,
		GracePeriod:       0,
		ScanInterval:      10 * time.Millisecond,
		MaxEdgesPerScan:   10,
		OnlyAutoGenerated: true,
	}, store)

	decay.ReinforceEdge("nornic:reinforced-edge")

	decay.Start(context.Background())
	decay.Stop()

	scanned, decayed, deleted, err := decay.TriggerScan(context.Background())
	require.NoError(t, err)
	assert.Equal(t, 4, scanned)
	assert.Equal(t, 2, decayed)
	assert.Equal(t, 1, deleted)
	assert.Contains(t, store.updated, storage.EdgeID("nornic:decay-me"))
	assert.Contains(t, store.deleted, storage.EdgeID("nornic:delete-me"))

	updatedEdge, err := store.GetEdge("nornic:decay-me")
	require.NoError(t, err)
	assert.Less(t, updatedEdge.Confidence, 0.9)
	assert.Greater(t, updatedEdge.Confidence, 0.3)

	_, err = store.GetEdge("nornic:delete-me")
	require.Error(t, err)

	manualEdge, err := store.GetEdge("nornic:manual-edge")
	require.NoError(t, err)
	assert.Equal(t, 0.4, manualEdge.Confidence)

	reinforcedEdge, err := store.GetEdge("nornic:reinforced-edge")
	require.NoError(t, err)
	assert.InDelta(t, 0.4, reinforcedEdge.Confidence, 0.0001)

	stats := decay.GetStats()
	assert.EqualValues(t, 1, stats.ScansCompleted)
	assert.EqualValues(t, 4, stats.EdgesScanned)
	assert.EqualValues(t, 2, stats.EdgesDecayed)
	assert.EqualValues(t, 1, stats.EdgesDeleted)
	assert.False(t, stats.LastScanTime.IsZero())
}

func TestEdgeDecay_DryRunAndDisabledModes(t *testing.T) {
	store := &trackingDecayEngine{MemoryEngine: storage.NewMemoryEngine()}
	_, err := store.CreateNode(&storage.Node{ID: "nornic:n1"})
	require.NoError(t, err)
	_, err = store.CreateNode(&storage.Node{ID: "nornic:n2"})
	require.NoError(t, err)

	old := time.Now().Add(-24 * time.Hour)
	createDecayFixtureEdge(t, store, &storage.Edge{
		ID:            "nornic:dry-run-delete",
		StartNode:     "nornic:n1",
		EndNode:       "nornic:n2",
		Type:          "RELATES_TO",
		Confidence:    0.4,
		AutoGenerated: true,
		CreatedAt:     old,
		UpdatedAt:     old,
	})

	dryRun := NewEdgeDecay(&EdgeDecayConfig{
		Enabled:           true,
		DecayRate:         0.5,
		MinConfidence:     0.3,
		GracePeriod:       0,
		ScanInterval:      time.Millisecond,
		OnlyAutoGenerated: true,
		DryRun:            true,
	}, store)

	scanned, decayed, deleted, err := dryRun.TriggerScan(context.Background())
	require.NoError(t, err)
	assert.Equal(t, 1, scanned)
	assert.Equal(t, 0, decayed)
	assert.Equal(t, 1, deleted)
	assert.Empty(t, store.deleted)

	edge, err := store.GetEdge("nornic:dry-run-delete")
	require.NoError(t, err)
	assert.Equal(t, 0.4, edge.Confidence)

	disabled := NewEdgeDecay(&EdgeDecayConfig{Enabled: false, ScanInterval: time.Millisecond}, store)
	disabled.Start(context.Background())
	assert.Nil(t, disabled.cancel)
	disabled.Stop()
}
