package resolvers

import (
	"time"

	"github.com/orneryd/nornicdb/pkg/graphql/models"
	"github.com/orneryd/nornicdb/pkg/nornicdb"
	"github.com/orneryd/nornicdb/pkg/storage"
)

// dbNodeToModel converts a nornicdb.Node to a GraphQL models.Node
func dbNodeToModel(node *nornicdb.Node) *models.Node {
	if node == nil {
		return nil
	}
	var createdAt *time.Time
	if !node.CreatedAt.IsZero() {
		createdAt = &node.CreatedAt
	}
	return &models.Node{
		ID:                  node.ID,
		InternalID:          node.ID,
		Labels:              node.Labels,
		Properties:          models.JSON(node.Properties),
		CreatedAt:           createdAt,
		HasEmbedding:        false, // Can't determine from Node type
		EmbeddingDimensions: 0,
	}
}

// storageNodeToModel converts a storage.Node to a GraphQL models.Node
func storageNodeToModel(node *storage.Node) *models.Node {
	if node == nil {
		return nil
	}
	var createdAt, updatedAt *time.Time
	if !node.CreatedAt.IsZero() {
		createdAt = &node.CreatedAt
	}
	if !node.UpdatedAt.IsZero() {
		updatedAt = &node.UpdatedAt
	}

	return &models.Node{
		ID:           string(node.ID),
		InternalID:   string(node.ID),
		Labels:       node.Labels,
		Properties:   models.JSON(node.Properties),
		CreatedAt:    createdAt,
		UpdatedAt:    updatedAt,
		HasEmbedding: len(node.ChunkEmbeddings) > 0 && len(node.ChunkEmbeddings[0]) > 0,
		EmbeddingDimensions: func() int {
			if len(node.ChunkEmbeddings) > 0 && len(node.ChunkEmbeddings[0]) > 0 {
				return len(node.ChunkEmbeddings[0])
			}
			return 0
		}(),
	}
}

// dbEdgeToModel converts a nornicdb.GraphEdge to a GraphQL models.Relationship
func dbEdgeToModel(edge *nornicdb.GraphEdge) *models.Relationship {
	if edge == nil {
		return nil
	}
	var createdAt *time.Time
	if !edge.CreatedAt.IsZero() {
		createdAt = &edge.CreatedAt
	}
	return &models.Relationship{
		ID:                 edge.ID,
		InternalID:         edge.ID,
		Type:               edge.Type,
		StartNodeID:        edge.Source,
		EndNodeID:          edge.Target,
		StartNodeElementID: edge.Source,
		EndNodeElementID:   edge.Target,
		Properties:         models.JSON(edge.Properties),
		CreatedAt:          createdAt,
		AutoGenerated:      false,
	}
}

// storageEdgeToModel converts a storage.Edge to a GraphQL models.Relationship
func storageEdgeToModel(edge *storage.Edge) *models.Relationship {
	if edge == nil {
		return nil
	}
	var createdAt, updatedAt *time.Time
	if !edge.CreatedAt.IsZero() {
		createdAt = &edge.CreatedAt
	}
	if !edge.UpdatedAt.IsZero() {
		updatedAt = &edge.UpdatedAt
	}
	confidence := edge.Confidence
	return &models.Relationship{
		ID:                 string(edge.ID),
		InternalID:         string(edge.ID),
		Type:               edge.Type,
		StartNodeID:        string(edge.StartNode),
		EndNodeID:          string(edge.EndNode),
		StartNodeElementID: string(edge.StartNode),
		EndNodeElementID:   string(edge.EndNode),
		Properties:         models.JSON(edge.Properties),
		CreatedAt:          createdAt,
		UpdatedAt:          updatedAt,
		Confidence:         &confidence,
		AutoGenerated:      edge.AutoGenerated,
	}
}
