package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.93

import (
	"context"

	"github.com/orneryd/nornicdb/pkg/graphql/generated"
	"github.com/orneryd/nornicdb/pkg/graphql/models"
)

// Rows is the resolver for the rows field.
func (r *cypherResultResolver) Rows(ctx context.Context, obj *models.CypherResult) ([][]models.JSON, error) {
	if obj == nil || obj.Rows == nil {
		return nil, nil
	}
	result := make([][]models.JSON, len(obj.Rows))
	for i, row := range obj.Rows {
		rowResult := make([]models.JSON, len(row))
		for j, val := range row {
			if m, ok := val.(map[string]interface{}); ok {
				rowResult[j] = models.JSON(m)
			} else {
				rowResult[j] = models.JSON{"value": val}
			}
		}
		result[i] = rowResult
	}
	return result, nil
}

// CreateNode is the resolver for the createNode field.
func (r *mutationResolver) CreateNode(ctx context.Context, input models.CreateNodeInput) (*models.Node, error) {
	return r.mutationCreateNode(ctx, input)
}

// UpdateNode is the resolver for the updateNode field.
func (r *mutationResolver) UpdateNode(ctx context.Context, input models.UpdateNodeInput) (*models.Node, error) {
	return r.mutationUpdateNode(ctx, input)
}

// DeleteNode is the resolver for the deleteNode field.
func (r *mutationResolver) DeleteNode(ctx context.Context, id string) (bool, error) {
	return r.mutationDeleteNode(ctx, id)
}

// BulkCreateNodes is the resolver for the bulkCreateNodes field.
func (r *mutationResolver) BulkCreateNodes(ctx context.Context, input models.BulkCreateNodesInput) (*models.BulkCreateResult, error) {
	return r.mutationBulkCreateNodes(ctx, input)
}

// BulkDeleteNodes is the resolver for the bulkDeleteNodes field.
func (r *mutationResolver) BulkDeleteNodes(ctx context.Context, ids []string) (*models.BulkDeleteResult, error) {
	return r.mutationBulkDeleteNodes(ctx, ids)
}

// MergeNode is the resolver for the mergeNode field.
func (r *mutationResolver) MergeNode(ctx context.Context, labels []string, matchProperties models.JSON, setProperties models.JSON) (*models.Node, error) {
	return r.mutationMergeNode(ctx, labels, matchProperties, setProperties)
}

// CreateRelationship is the resolver for the createRelationship field.
func (r *mutationResolver) CreateRelationship(ctx context.Context, input models.CreateRelationshipInput) (*models.Relationship, error) {
	return r.mutationCreateRelationship(ctx, input)
}

// UpdateRelationship is the resolver for the updateRelationship field.
func (r *mutationResolver) UpdateRelationship(ctx context.Context, input models.UpdateRelationshipInput) (*models.Relationship, error) {
	return r.mutationUpdateRelationship(ctx, input)
}

// DeleteRelationship is the resolver for the deleteRelationship field.
func (r *mutationResolver) DeleteRelationship(ctx context.Context, id string) (bool, error) {
	return r.mutationDeleteRelationship(ctx, id)
}

// BulkCreateRelationships is the resolver for the bulkCreateRelationships field.
func (r *mutationResolver) BulkCreateRelationships(ctx context.Context, input models.BulkCreateRelationshipsInput) (*models.BulkCreateResult, error) {
	return r.mutationBulkCreateRelationships(ctx, input)
}

// BulkDeleteRelationships is the resolver for the bulkDeleteRelationships field.
func (r *mutationResolver) BulkDeleteRelationships(ctx context.Context, ids []string) (*models.BulkDeleteResult, error) {
	return r.mutationBulkDeleteRelationships(ctx, ids)
}

// MergeRelationship is the resolver for the mergeRelationship field.
func (r *mutationResolver) MergeRelationship(ctx context.Context, startNodeID string, endNodeID string, typeArg string, properties models.JSON) (*models.Relationship, error) {
	return r.mutationMergeRelationship(ctx, startNodeID, endNodeID, typeArg, properties)
}

// ExecuteCypher is the resolver for the executeCypher field.
func (r *mutationResolver) ExecuteCypher(ctx context.Context, input models.CypherInput) (*models.CypherResult, error) {
	return r.mutationExecuteCypher(ctx, input)
}

// TriggerEmbedding is the resolver for the triggerEmbedding field.
func (r *mutationResolver) TriggerEmbedding(ctx context.Context, regenerate *bool) (*models.EmbeddingStatus, error) {
	return r.mutationTriggerEmbedding(ctx, regenerate)
}

// RebuildSearchIndex is the resolver for the rebuildSearchIndex field.
func (r *mutationResolver) RebuildSearchIndex(ctx context.Context) (bool, error) {
	return r.mutationRebuildSearchIndex(ctx)
}

// RunDecay is the resolver for the runDecay field.
func (r *mutationResolver) RunDecay(ctx context.Context) (*models.DecayResult, error) {
	return r.mutationRunDecay(ctx)
}

// ClearAll is the resolver for the clearAll field.
func (r *mutationResolver) ClearAll(ctx context.Context, confirmPhrase string) (bool, error) {
	return r.mutationClearAll(ctx, confirmPhrase)
}

// Relationships is the resolver for the relationships field.
func (r *nodeResolver) Relationships(ctx context.Context, obj *models.Node, types []string, direction *models.RelationshipDirection, limit *int) ([]models.Relationship, error) {
	return r.nodeRelationships(ctx, obj, types, direction, limit)
}

// Outgoing is the resolver for the outgoing field.
func (r *nodeResolver) Outgoing(ctx context.Context, obj *models.Node, types []string, limit *int) ([]models.Relationship, error) {
	return r.nodeOutgoing(ctx, obj, types, limit)
}

// Incoming is the resolver for the incoming field.
func (r *nodeResolver) Incoming(ctx context.Context, obj *models.Node, types []string, limit *int) ([]models.Relationship, error) {
	return r.nodeIncoming(ctx, obj, types, limit)
}

// Neighbors is the resolver for the neighbors field.
func (r *nodeResolver) Neighbors(ctx context.Context, obj *models.Node, direction *models.RelationshipDirection, relationshipTypes []string, labels []string, limit *int) ([]models.Node, error) {
	return r.nodeNeighbors(ctx, obj, direction, relationshipTypes, labels, limit)
}

// Similar is the resolver for the similar field.
func (r *nodeResolver) Similar(ctx context.Context, obj *models.Node, limit *int, threshold *float64) ([]models.SimilarNode, error) {
	return r.nodeSimilar(ctx, obj, limit, threshold)
}

// Node is the resolver for the node field.
func (r *queryResolver) Node(ctx context.Context, id string) (*models.Node, error) {
	return r.queryNode(ctx, id)
}

// Nodes is the resolver for the nodes field.
func (r *queryResolver) Nodes(ctx context.Context, ids []string) ([]models.Node, error) {
	return r.queryNodes(ctx, ids)
}

// AllNodes is the resolver for the allNodes field.
func (r *queryResolver) AllNodes(ctx context.Context, labels []string, limit *int, offset *int) ([]models.Node, error) {
	return r.queryAllNodes(ctx, labels, limit, offset)
}

// NodesByLabel is the resolver for the nodesByLabel field.
func (r *queryResolver) NodesByLabel(ctx context.Context, label string, limit *int, offset *int) ([]models.Node, error) {
	return r.queryNodesByLabel(ctx, label, limit, offset)
}

// NodeCount is the resolver for the nodeCount field.
func (r *queryResolver) NodeCount(ctx context.Context, label *string) (int, error) {
	return r.queryNodeCount(ctx, label)
}

// Relationship is the resolver for the relationship field.
func (r *queryResolver) Relationship(ctx context.Context, id string) (*models.Relationship, error) {
	return r.queryRelationship(ctx, id)
}

// AllRelationships is the resolver for the allRelationships field.
func (r *queryResolver) AllRelationships(ctx context.Context, types []string, limit *int, offset *int) ([]models.Relationship, error) {
	return r.queryAllRelationships(ctx, types, limit, offset)
}

// RelationshipsByType is the resolver for the relationshipsByType field.
func (r *queryResolver) RelationshipsByType(ctx context.Context, typeArg string, limit *int, offset *int) ([]models.Relationship, error) {
	return r.queryRelationshipsByType(ctx, typeArg, limit, offset)
}

// RelationshipsBetween is the resolver for the relationshipsBetween field.
func (r *queryResolver) RelationshipsBetween(ctx context.Context, startNodeID string, endNodeID string) ([]models.Relationship, error) {
	return r.queryRelationshipsBetween(ctx, startNodeID, endNodeID)
}

// RelationshipCount is the resolver for the relationshipCount field.
func (r *queryResolver) RelationshipCount(ctx context.Context, typeArg *string) (int, error) {
	return r.queryRelationshipCount(ctx, typeArg)
}

// Search is the resolver for the search field.
func (r *queryResolver) Search(ctx context.Context, query string, options *models.SearchOptions) (*models.SearchResponse, error) {
	return r.querySearch(ctx, query, options)
}

// Similar is the resolver for the similar field.
func (r *queryResolver) Similar(ctx context.Context, nodeID string, limit *int, threshold *float64) ([]models.SimilarNode, error) {
	return r.querySimilar(ctx, nodeID, limit, threshold)
}

// SearchByProperty is the resolver for the searchByProperty field.
func (r *queryResolver) SearchByProperty(ctx context.Context, key string, value models.JSON, labels []string, limit *int) ([]models.Node, error) {
	return r.querySearchByProperty(ctx, key, value, labels, limit)
}

// Cypher is the resolver for the cypher field.
func (r *queryResolver) Cypher(ctx context.Context, input models.CypherInput) (*models.CypherResult, error) {
	return r.queryCypher(ctx, input)
}

// Stats is the resolver for the stats field.
func (r *queryResolver) Stats(ctx context.Context) (*models.DatabaseStats, error) {
	return r.queryStats(ctx)
}

// Schema is the resolver for the schema field.
func (r *queryResolver) Schema(ctx context.Context) (*models.GraphSchema, error) {
	return r.querySchema(ctx)
}

// Labels is the resolver for the labels field.
func (r *queryResolver) Labels(ctx context.Context) ([]string, error) {
	return r.queryLabels(ctx)
}

// RelationshipTypes is the resolver for the relationshipTypes field.
func (r *queryResolver) RelationshipTypes(ctx context.Context) ([]string, error) {
	return r.queryRelationshipTypes(ctx)
}

// ShortestPath is the resolver for the shortestPath field.
func (r *queryResolver) ShortestPath(ctx context.Context, startNodeID string, endNodeID string, maxDepth *int, relationshipTypes []string) ([]models.Node, error) {
	return r.queryShortestPath(ctx, startNodeID, endNodeID, maxDepth, relationshipTypes)
}

// AllPaths is the resolver for the allPaths field.
func (r *queryResolver) AllPaths(ctx context.Context, startNodeID string, endNodeID string, maxDepth *int, limit *int) ([][]models.Node, error) {
	return r.queryAllPaths(ctx, startNodeID, endNodeID, maxDepth, limit)
}

// Neighborhood is the resolver for the neighborhood field.
func (r *queryResolver) Neighborhood(ctx context.Context, nodeID string, depth *int, relationshipTypes []string, labels []string, limit *int) (*models.Subgraph, error) {
	return r.queryNeighborhood(ctx, nodeID, depth, relationshipTypes, labels, limit)
}

// StartNode is the resolver for the startNode field.
func (r *relationshipResolver) StartNode(ctx context.Context, obj *models.Relationship) (*models.Node, error) {
	return r.relationshipStartNode(ctx, obj)
}

// EndNode is the resolver for the endNode field.
func (r *relationshipResolver) EndNode(ctx context.Context, obj *models.Relationship) (*models.Node, error) {
	return r.relationshipEndNode(ctx, obj)
}

// NodeCreated is the resolver for the nodeCreated field.
func (r *subscriptionResolver) NodeCreated(ctx context.Context, labels []string) (<-chan *models.Node, error) {
	return r.subscriptionNodeCreated(ctx, labels)
}

// NodeUpdated is the resolver for the nodeUpdated field.
func (r *subscriptionResolver) NodeUpdated(ctx context.Context, id *string, labels []string) (<-chan *models.Node, error) {
	return r.subscriptionNodeUpdated(ctx, id, labels)
}

// NodeDeleted is the resolver for the nodeDeleted field.
func (r *subscriptionResolver) NodeDeleted(ctx context.Context, labels []string) (<-chan string, error) {
	return r.subscriptionNodeDeleted(ctx, labels)
}

// RelationshipCreated is the resolver for the relationshipCreated field.
func (r *subscriptionResolver) RelationshipCreated(ctx context.Context, types []string) (<-chan *models.Relationship, error) {
	return r.subscriptionRelationshipCreated(ctx, types)
}

// RelationshipUpdated is the resolver for the relationshipUpdated field.
func (r *subscriptionResolver) RelationshipUpdated(ctx context.Context, id *string, types []string) (<-chan *models.Relationship, error) {
	return r.subscriptionRelationshipUpdated(ctx, id, types)
}

// RelationshipDeleted is the resolver for the relationshipDeleted field.
func (r *subscriptionResolver) RelationshipDeleted(ctx context.Context, types []string) (<-chan string, error) {
	return r.subscriptionRelationshipDeleted(ctx, types)
}

// SearchStream is the resolver for the searchStream field.
func (r *subscriptionResolver) SearchStream(ctx context.Context, query string, options *models.SearchOptions) (<-chan *models.SearchResult, error) {
	return r.subscriptionSearchStream(ctx, query, options)
}

// CypherResult returns generated.CypherResultResolver implementation.
func (r *Resolver) CypherResult() generated.CypherResultResolver { return &cypherResultResolver{r} }

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Node returns generated.NodeResolver implementation.
func (r *Resolver) Node() generated.NodeResolver { return &nodeResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

// Relationship returns generated.RelationshipResolver implementation.
func (r *Resolver) Relationship() generated.RelationshipResolver { return &relationshipResolver{r} }

// Subscription returns generated.SubscriptionResolver implementation.
func (r *Resolver) Subscription() generated.SubscriptionResolver { return &subscriptionResolver{r} }

type (
	cypherResultResolver struct{ *Resolver }
	mutationResolver     struct{ *Resolver }
	nodeResolver         struct{ *Resolver }
	queryResolver        struct{ *Resolver }
	relationshipResolver struct{ *Resolver }
	subscriptionResolver struct{ *Resolver }
)
