package storage

import (
	"encoding/binary"
	"fmt"
	"math"
	"time"

	"github.com/dgraph-io/badger/v4"
	"github.com/orneryd/nornicdb/pkg/util"
	"github.com/vmihailenco/msgpack/v5"
)

// Compact on-disk edge format.
//
// Rationale: the default gob/msgpack-serialized edge carries field names
// ("ID", "StartNode", "EndNode", "Type", "Properties", "CreatedAt",
// "UpdatedAt", "Confidence", ...) plus full 40–50-byte UUID strings for
// the IDs. On a 300k-edge graph that's ~30-40 MiB of field-name and
// string-ID overhead per body prefix.
//
// The compact format below:
//   - Drops Edge.ID entirely (it's the key suffix — callers reconstruct
//     it from the lookup key).
//   - Stores StartNode / EndNode as 8-byte numeric IDs backed by the
//     engine's id dictionary. Readers resolve the numIDs to full string
//     IDs via the dictionary's reverse map.
//   - Stores scalar metadata (CreatedAt, UpdatedAt, Confidence, flags)
//     as fixed-width binary.
//   - Uses msgpack for just the Type string + Properties map (the one
//     field that genuinely varies per edge).
//
// Layout:
//
//	[0]        : format byte (edgeFormatCompactV1 = 0x02)
//	[1]        : flags (bit 0 = AutoGenerated, bit 1 = VisibilitySuppressed)
//	[2..9]     : StartNode numID (big-endian uint64)
//	[10..17]   : EndNode numID
//	[18..25]   : CreatedAt nanos (int64)
//	[26..33]   : UpdatedAt nanos (int64)
//	[34..41]   : Confidence (uint64 bit-pattern of float64)
//	[42..]     : varint(typeLen) + typeBytes
//	[...]      : msgpack(Properties)
//
// Legacy gob/msgpack-wrapped bodies still decode through the existing
// deserializeEdge path — we look at the first byte to pick.
const (
	edgeFormatCompactV1 byte = 0x02
	edgeFlagAutoGen     byte = 1 << 0
	edgeFlagSuppressed  byte = 1 << 1
)

// encodeEdgeCompactWithNums assembles the compact body given pre-resolved
// endpoint numIDs. The caller is responsible for invoking the id dict to
// allocate numIDs in the enclosing txn.
func encodeEdgeCompactWithNums(edge *Edge, startNum, endNum uint64) ([]byte, error) {
	if err := validatePropertiesForStorage(edge.Properties); err != nil {
		return nil, fmt.Errorf("invalid edge properties: %w", err)
	}
	typeBytes := []byte(edge.Type)
	propsBytes, err := msgpack.Marshal(edge.Properties)
	if err != nil {
		return nil, fmt.Errorf("marshaling edge properties: %w", err)
	}

	// Pre-size the buffer so we do one allocation.
	header := 1 + 1 + 8 + 8 + 8 + 8 + 8 // format, flags, start, end, created, updated, confidence
	// varint type length (worst-case 5 bytes for uint32-sized lengths)
	buf := make([]byte, 0, header+5+len(typeBytes)+len(propsBytes))
	buf = append(buf, edgeFormatCompactV1)

	var flags byte
	if edge.AutoGenerated {
		flags |= edgeFlagAutoGen
	}
	if edge.VisibilitySuppressed {
		flags |= edgeFlagSuppressed
	}
	buf = append(buf, flags)

	var scratch [8]byte
	binary.BigEndian.PutUint64(scratch[:], startNum)
	buf = append(buf, scratch[:]...)
	binary.BigEndian.PutUint64(scratch[:], endNum)
	buf = append(buf, scratch[:]...)
	binary.BigEndian.PutUint64(scratch[:], uint64(edge.CreatedAt.UTC().UnixNano()))
	buf = append(buf, scratch[:]...)
	binary.BigEndian.PutUint64(scratch[:], uint64(edge.UpdatedAt.UTC().UnixNano()))
	buf = append(buf, scratch[:]...)
	binary.BigEndian.PutUint64(scratch[:], math.Float64bits(edge.Confidence))
	buf = append(buf, scratch[:]...)

	buf = binary.AppendUvarint(buf, uint64(len(typeBytes)))
	buf = append(buf, typeBytes...)
	buf = append(buf, propsBytes...)
	return buf, nil
}

// decodeEdgeCompact parses a compact edge body. Returns ErrNotCompactEdge
// if the data isn't in the compact format (callers should fall back to
// the legacy gob/msgpack path). Leaves Edge.ID, StartNode, EndNode empty —
// the caller fills them from the key + id dictionary lookup.
func decodeEdgeCompact(data []byte) (*Edge, uint64, uint64, error) {
	if len(data) < 1 || data[0] != edgeFormatCompactV1 {
		return nil, 0, 0, errNotCompactEdge
	}
	if len(data) < 1+1+8+8+8+8+8 {
		return nil, 0, 0, fmt.Errorf("compact edge truncated: %d bytes", len(data))
	}
	offset := 1
	flags := data[offset]
	offset++
	startNum := binary.BigEndian.Uint64(data[offset : offset+8])
	offset += 8
	endNum := binary.BigEndian.Uint64(data[offset : offset+8])
	offset += 8
	createdNs := int64(binary.BigEndian.Uint64(data[offset : offset+8]))
	offset += 8
	updatedNs := int64(binary.BigEndian.Uint64(data[offset : offset+8]))
	offset += 8
	confidence := math.Float64frombits(binary.BigEndian.Uint64(data[offset : offset+8]))
	offset += 8

	typeLen, n := binary.Uvarint(data[offset:])
	if n <= 0 {
		return nil, 0, 0, fmt.Errorf("compact edge: invalid type length varint")
	}
	offset += n
	if offset+int(typeLen) > len(data) {
		return nil, 0, 0, fmt.Errorf("compact edge: type exceeds payload")
	}
	edgeType := string(data[offset : offset+int(typeLen)])
	offset += int(typeLen)

	var props map[string]any
	if offset < len(data) {
		if err := util.DecodeMsgpackBytes(data[offset:], &props); err != nil {
			return nil, 0, 0, fmt.Errorf("compact edge: decoding properties: %w", err)
		}
	}

	edge := &Edge{
		Type:                 edgeType,
		Properties:           props,
		CreatedAt:            time.Unix(0, createdNs).UTC(),
		UpdatedAt:            time.Unix(0, updatedNs).UTC(),
		Confidence:           confidence,
		AutoGenerated:        flags&edgeFlagAutoGen != 0,
		VisibilitySuppressed: flags&edgeFlagSuppressed != 0,
	}
	return edge, startNum, endNum, nil
}

var errNotCompactEdge = fmt.Errorf("not a compact edge body")

// encodeEdgeInTxn resolves (allocating if needed) endpoint numIDs via the
// id dictionary and emits a compact edge body. Callers should use this in
// place of encodeEdge on the write path to keep stored edges tight.
func (b *BadgerEngine) encodeEdgeInTxn(txn *badger.Txn, edge *Edge) ([]byte, error) {
	startNum, err := b.idDict.resolveOrAllocateNodeNumIDInTxn(txn, edge.StartNode)
	if err != nil {
		return nil, fmt.Errorf("allocating start node numID: %w", err)
	}
	endNum, err := b.idDict.resolveOrAllocateNodeNumIDInTxn(txn, edge.EndNode)
	if err != nil {
		return nil, fmt.Errorf("allocating end node numID: %w", err)
	}
	return encodeEdgeCompactWithNums(edge, startNum, endNum)
}

// decodeEdgeBody dispatches to the compact decoder when the body starts
// with edgeFormatCompactV1, otherwise falls back to the legacy
// gob/msgpack path via decodeEdge. Fills Edge.StartNode / EndNode by
// looking up the numID via the id dictionary's reverse map.
//
// Edge.ID is intentionally left empty on the compact path — the caller
// recovers it from the badger key context. For callers that already
// have the edge ID (most do, since they either did txn.Get(edgeKey(id))
// or they pulled the ID from a secondary index), use decodeEdgeBodyWithID.
func (b *BadgerEngine) decodeEdgeBody(data []byte) (*Edge, error) {
	return b.decodeEdgeBodyWithID(data, "")
}

// decodeEdgeBodyWithID is decodeEdgeBody with a caller-supplied edge ID.
// Populates Edge.ID when the compact decoder omits it; the legacy path
// already stores the ID in the body and ignores the supplied hint.
func (b *BadgerEngine) decodeEdgeBodyWithID(data []byte, id EdgeID) (*Edge, error) {
	if len(data) >= 1 && data[0] == edgeFormatCompactV1 {
		edge, startNum, endNum, err := decodeEdgeCompact(data)
		if err != nil {
			return nil, err
		}
		startID, ok := b.idDict.lookupNodeIDByNum(startNum)
		if !ok {
			return nil, fmt.Errorf("compact edge: start numID %d not in dict", startNum)
		}
		endID, ok := b.idDict.lookupNodeIDByNum(endNum)
		if !ok {
			return nil, fmt.Errorf("compact edge: end numID %d not in dict", endNum)
		}
		edge.ID = id
		edge.StartNode = startID
		edge.EndNode = endID
		return edge, nil
	}
	edge, err := decodeEdge(data)
	if err != nil {
		return nil, err
	}
	if edge != nil && id != "" {
		edge.ID = id
	}
	return edge, nil
}
