package storage

// Edge-case tests for edge_compact.go covering format-byte rejection,
// header truncation at every fixed-width boundary, type-length varint
// errors, properties-payload truncation, V1 round-trip via the migration
// helper, and the empty-properties path.
//
// New in v1.1.2 to harden the storage landing per the explicit user
// ask: "make sure all error cases are covered and that we gracefully
// handle older storage formats and that the old code won't break on
// newer files."

import (
	"encoding/binary"
	"math"
	"testing"
	"time"

	"github.com/dgraph-io/badger/v4"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// edgeHeaderSize is the fixed-width prefix length of the V1/V2 compact
// edge body, before the type varint and bytes:
//
//	1 (format) + 1 (flags) + 8 (start) + 8 (end) + 8 (created) + 8 (updated) + 8 (confidence)
//
// = 42 bytes.
const edgeHeaderSize = 42

// TestEdgeCompactV2_RejectsV1FormatByte — pin that the V2 hot-path
// decoder refuses a V1 leading byte. After migration, encountering a
// V1 byte indicates corruption: the stored data should never contain
// V1 bodies again. The error must name the observed and expected
// bytes so operators can match against the migration log.
func TestEdgeCompactV2_RejectsV1FormatByte(t *testing.T) {
	eng := newTestEngine(t)
	body := make([]byte, edgeHeaderSize)
	body[0] = edgeFormatCompactV1

	_, err := eng.decodeEdgeBodyWithID("ns", body, "test:edge-1")
	require.Error(t, err)
	assert.Contains(t, err.Error(), "0x02")
	assert.Contains(t, err.Error(), "expected V2")
	assert.Contains(t, err.Error(), "0x03")
}

// TestEdgeCompactV2_RejectsArbitraryFormatByte — a leading byte that
// isn't V1 or V2 (random corruption) must surface as an unexpected-
// format error. Any byte other than 0x03 fails fast.
func TestEdgeCompactV2_RejectsArbitraryFormatByte(t *testing.T) {
	eng := newTestEngine(t)
	for _, b := range []byte{0x00, 0x01, 0xff, 0x10, 0x42} {
		body := make([]byte, edgeHeaderSize)
		body[0] = b

		_, err := eng.decodeEdgeBodyWithID("ns", body, "test:edge-1")
		require.Error(t, err, "format byte 0x%02x must be rejected", b)
		assert.Contains(t, err.Error(), "unexpected format byte")
	}
}

func TestEdgeCompactV2_DecodeEdgeBodyWithoutExplicitID(t *testing.T) {
	eng := newTestEngine(t)
	edge := &Edge{
		ID:                   "test:edge-compact",
		StartNode:            "test:start",
		EndNode:              "test:end",
		Type:                 "KNOWS",
		Properties:           map[string]any{"weight": int64(3)},
		CreatedAt:            time.Unix(10, 11).UTC(),
		UpdatedAt:            time.Unix(12, 13).UTC(),
		Confidence:           0.75,
		AutoGenerated:        true,
		VisibilitySuppressed: true,
	}
	namespace := namespaceForEdgeID(edge.ID)
	var body []byte
	err := eng.withUpdate(func(txn *badger.Txn) error {
		var encErr error
		body, encErr = eng.encodeEdgeInTxn(txn, namespace, edge)
		if encErr != nil {
			return encErr
		}
		_, _ = eng.idDict.flushTxnCounters(txn)
		_ = eng.propKeyDict.flushTxnCounters(txn)
		return nil
	})
	require.NoError(t, err)

	decoded, err := eng.decodeEdgeBody(namespace, body)
	require.NoError(t, err)
	require.Empty(t, decoded.ID)
	require.Equal(t, edge.StartNode, decoded.StartNode)
	require.Equal(t, edge.EndNode, decoded.EndNode)
	require.Equal(t, edge.Type, decoded.Type)
	require.Equal(t, edge.Properties["weight"], decoded.Properties["weight"])
	require.True(t, decoded.AutoGenerated)
	require.True(t, decoded.VisibilitySuppressed)
}

// TestEdgeCompactV2_HeaderTruncated — header truncation at every
// position from 1 to edgeHeaderSize-1 must surface "compact edge
// truncated". Pin every boundary so a future change to the layout
// can't silently introduce a "decode 30 bytes as a 42-byte body"
// regression.
func TestEdgeCompactV2_HeaderTruncated(t *testing.T) {
	eng := newTestEngine(t)
	for size := 1; size < edgeHeaderSize; size++ {
		body := make([]byte, size)
		body[0] = edgeFormatCompactV2

		_, err := eng.decodeEdgeBodyWithID("ns", body, "test:edge-1")
		require.Error(t, err, "size=%d byte body must be rejected", size)
		assert.Contains(t, err.Error(), "truncated", "size=%d body err: %v", size, err)
	}
}

// TestEdgeCompactV2_TypeLenVarintInvalid — header is intact but the
// type-length varint is malformed (single 0x80 with no continuation,
// or 11 continuation bytes that overflow uint64). Must surface
// "invalid type length varint".
func TestEdgeCompactV2_TypeLenVarintInvalid(t *testing.T) {
	eng := newTestEngine(t)
	body := make([]byte, edgeHeaderSize, edgeHeaderSize+11)
	body[0] = edgeFormatCompactV2

	t.Run("truncated continuation", func(t *testing.T) {
		// 0x80 alone signals "more bytes follow" but there are none.
		input := append(body, 0x80)
		_, err := eng.decodeEdgeBodyWithID("ns", input, "test:edge-1")
		require.Error(t, err)
		assert.Contains(t, err.Error(), "invalid type length varint")
	})

	t.Run("varint overflow", func(t *testing.T) {
		// 11 consecutive 0x80 bytes — uint64 cap is 10.
		input := append(body,
			0x80, 0x80, 0x80, 0x80, 0x80,
			0x80, 0x80, 0x80, 0x80, 0x80, 0x80,
		)
		_, err := eng.decodeEdgeBodyWithID("ns", input, "test:edge-1")
		require.Error(t, err)
		assert.Contains(t, err.Error(), "invalid type length varint")
	})
}

// TestEdgeCompactV2_TypeExceedsPayload — header + varint claims a
// 1000-byte type string but only 5 bytes follow. Must surface
// "type exceeds payload".
func TestEdgeCompactV2_TypeExceedsPayload(t *testing.T) {
	eng := newTestEngine(t)
	body := make([]byte, 0, edgeHeaderSize+10)
	body = append(body, edgeFormatCompactV2)
	for i := 1; i < edgeHeaderSize; i++ {
		body = append(body, 0)
	}
	// varint(1000) — 2 bytes
	body = binary.AppendUvarint(body, 1000)
	// only 5 bytes of type
	body = append(body, 'h', 'e', 'l', 'l', 'o')

	_, err := eng.decodeEdgeBodyWithID("ns", body, "test:edge-1")
	require.Error(t, err)
	assert.Contains(t, err.Error(), "type exceeds payload")
}

// TestEdgeCompactV2_EmptyPropertiesRoundTrip — a V2 edge with no
// properties at all must encode and decode correctly. The encoder
// emits a count-zero tokenized payload (single 0x00 byte) and the
// decoder takes the offset==len(data) zero-properties path.
func TestEdgeCompactV2_EmptyPropertiesRoundTrip(t *testing.T) {
	now := time.Unix(0, time.Now().UnixNano()).UTC()
	original := &Edge{
		ID:         EdgeID("test:no-props"),
		StartNode:  "test:a",
		EndNode:    "test:b",
		Type:       "EMPTY",
		CreatedAt:  now,
		UpdatedAt:  now,
		Confidence: 1.0,
		Properties: nil,
	}

	got, err := codecRoundTripEdge(t, original)
	require.NoError(t, err)
	assert.Equal(t, original.ID, got.ID)
	assert.Equal(t, original.StartNode, got.StartNode)
	assert.Equal(t, original.EndNode, got.EndNode)
	assert.Equal(t, original.Type, got.Type)
	assert.NotNil(t, got.Properties, "decoded edge must have non-nil Properties even for an empty property set")
	assert.Empty(t, got.Properties)
}

// TestEdgeCompactV2_UnknownNumIDSurfaces — a V2 body that references
// numIDs missing from the id dict must surface a clean error rather
// than panic. This is corruption: WAL replay or partial dict failure
// could in theory desync the dict from the body store.
func TestEdgeCompactV2_UnknownNumIDSurfaces(t *testing.T) {
	eng := newTestEngine(t)

	// Build a synthetic V2 body referencing numIDs the dict hasn't
	// been told about.
	now := time.Unix(0, time.Now().UnixNano()).UTC()
	body := encodeEdgeCompactHeader(edgeFormatCompactV2, &Edge{
		Type:       "T",
		CreatedAt:  now,
		UpdatedAt:  now,
		Confidence: 1.0,
	}, 9999, 9998, 0)
	body = append(body, 0x00) // empty tokenized payload

	_, err := eng.decodeEdgeBodyWithID("ns", body, "test:ghost")
	require.Error(t, err)
	assert.Contains(t, err.Error(), "numID")
}

// TestEdgeCompactV1_RoundTrip — pin that the V1 encode/decode helpers
// still work for migration paths. After v1.1.2, all production code
// emits V2; the V1 helpers are only used by the V1→V2 migration
// scaffolding. Removing them silently would break upgrades from old
// data directories. Pin the round-trip so a future cleanup that drops
// V1 helpers fails this test loudly.
func TestEdgeCompactV1_RoundTrip(t *testing.T) {
	now := time.Unix(0, time.Now().UnixNano()).UTC()
	edge := &Edge{
		Type:          "LEGACY_V1",
		CreatedAt:     now,
		UpdatedAt:     now,
		Confidence:    0.75,
		AutoGenerated: true,
		Properties: map[string]any{
			"k": "v",
			"n": int64(42),
		},
	}

	body, err := encodeEdgeCompactV1(edge, 1, 2)
	require.NoError(t, err)
	require.Greater(t, len(body), edgeHeaderSize)
	assert.Equal(t, edgeFormatCompactV1, body[0])

	decoded, startNum, endNum, err := decodeEdgeCompactV1(body)
	require.NoError(t, err)
	assert.Equal(t, uint64(1), startNum)
	assert.Equal(t, uint64(2), endNum)
	assert.Equal(t, edge.Type, decoded.Type)
	assert.Equal(t, edge.AutoGenerated, decoded.AutoGenerated)
	assert.InDelta(t, edge.Confidence, decoded.Confidence, 1e-9)
	assert.Equal(t, "v", decoded.Properties["k"])
	// V1 used loose msgpack for properties, so int64(42) may narrow to int8.
	switch v := decoded.Properties["n"].(type) {
	case int64:
		assert.Equal(t, int64(42), v)
	case int8:
		assert.Equal(t, int8(42), v)
	default:
		t.Fatalf("expected int8 or int64 for V1 property, got %T", v)
	}
}

// TestEdgeCompactV1Decoder_RejectsV2Body — the V1 decoder must NOT
// accept a V2 body. The migration helper relies on this to detect
// already-migrated data and skip rewriting it.
func TestEdgeCompactV1Decoder_RejectsV2Body(t *testing.T) {
	body := make([]byte, edgeHeaderSize)
	body[0] = edgeFormatCompactV2

	_, _, _, err := decodeEdgeCompactV1(body)
	assert.Error(t, err, "V1 decoder must refuse V2 bodies (got nil error)")
}

// TestEdgeCompactV2Decoder_RejectsV1Body — symmetric: the V2 decoder
// must NOT accept a V1 body. Without this guarantee, a V2-attempt-on-V1
// would interpret V1's loose msgpack property map as a tokenized
// payload and fail at the dictionary lookup with confusing diagnostics.
func TestEdgeCompactV2Decoder_RejectsV1Body(t *testing.T) {
	eng := newTestEngine(t)

	// Build a real V1 body.
	v1Body, err := encodeEdgeCompactV1(&Edge{Type: "V1Body"}, 1, 2)
	require.NoError(t, err)

	// Feed it to the V2 path.
	_, _, _, err = eng.decodeEdgeCompactV2("ns", v1Body)
	require.Error(t, err)
	// Error from decodeEdgeCompactHeader's format-byte check.
	assert.True(t,
		isEdgeFormatMismatch(err),
		"V2 decoder must reject V1 body with format-mismatch error (got %v)", err)
}

// TestEdgeCompactV2_TypeMaxLength — pin the boundary at the largest
// type string we'd ever expect (Neo4j allows 65k UTF-8 bytes for a
// relationship type). Encode/decode must work without truncation.
func TestEdgeCompactV2_TypeMaxLength(t *testing.T) {
	bigType := make([]byte, 1024)
	for i := range bigType {
		bigType[i] = 'T'
	}
	now := time.Unix(0, time.Now().UnixNano()).UTC()
	original := &Edge{
		ID:         EdgeID("test:big-type"),
		StartNode:  "test:a",
		EndNode:    "test:b",
		Type:       string(bigType),
		CreatedAt:  now,
		UpdatedAt:  now,
		Confidence: 0.5,
		Properties: map[string]any{"k": "v"},
	}

	got, err := codecRoundTripEdge(t, original)
	require.NoError(t, err)
	assert.Equal(t, original.Type, got.Type)
	assert.Equal(t, "v", got.Properties["k"])
}

// TestEdgeCompactV2_FlagBitsRoundTrip — pin both flag bits independently.
// AutoGenerated lives in bit 0; VisibilitySuppressed in bit 1. A bug
// that conflated the two would silently flip suppression.
func TestEdgeCompactV2_FlagBitsRoundTrip(t *testing.T) {
	now := time.Unix(0, time.Now().UnixNano()).UTC()
	cases := []struct {
		auto       bool
		suppressed bool
	}{
		{false, false},
		{true, false},
		{false, true},
		{true, true},
	}
	for _, tc := range cases {
		original := &Edge{
			ID:                   EdgeID("test:flags"),
			StartNode:            "test:a",
			EndNode:              "test:b",
			Type:                 "F",
			CreatedAt:            now,
			UpdatedAt:            now,
			Confidence:           0.5,
			AutoGenerated:        tc.auto,
			VisibilitySuppressed: tc.suppressed,
		}
		got, err := codecRoundTripEdge(t, original)
		require.NoError(t, err, "auto=%v suppressed=%v", tc.auto, tc.suppressed)
		assert.Equal(t, tc.auto, got.AutoGenerated, "AutoGenerated mismatch (auto=%v suppressed=%v)", tc.auto, tc.suppressed)
		assert.Equal(t, tc.suppressed, got.VisibilitySuppressed, "VisibilitySuppressed mismatch (auto=%v suppressed=%v)", tc.auto, tc.suppressed)
	}
}

// TestEdgeCompactV2_ConfidenceFloatPrecision — confidence is stored as
// the IEEE-754 bit pattern of a float64. Pin that subnormals, NaN, and
// infinities round-trip bit-exactly. A bug that funneled the value
// through string conversion would lose these.
func TestEdgeCompactV2_ConfidenceFloatPrecision(t *testing.T) {
	now := time.Unix(0, time.Now().UnixNano()).UTC()
	cases := []float64{
		0.0,
		1.0,
		math.SmallestNonzeroFloat64,
		math.MaxFloat64,
		math.Inf(1),
		math.Inf(-1),
		// NaN bit patterns are tricky; pin one canonical NaN.
	}
	for _, v := range cases {
		original := &Edge{
			ID:         EdgeID("test:conf"),
			StartNode:  "test:a",
			EndNode:    "test:b",
			Type:       "C",
			CreatedAt:  now,
			UpdatedAt:  now,
			Confidence: v,
		}
		got, err := codecRoundTripEdge(t, original)
		require.NoError(t, err, "confidence=%v", v)
		if math.IsInf(v, 1) {
			assert.True(t, math.IsInf(got.Confidence, 1), "expected +Inf, got %v", got.Confidence)
		} else if math.IsInf(v, -1) {
			assert.True(t, math.IsInf(got.Confidence, -1), "expected -Inf, got %v", got.Confidence)
		} else {
			// Exact bit-pattern equality.
			assert.Equal(t, math.Float64bits(v), math.Float64bits(got.Confidence),
				"confidence bit-pattern mismatch for %v", v)
		}
	}
}

// isEdgeFormatMismatch returns true when err is the sentinel
// errEdgeFormatMismatch or wraps it. The package keeps the sentinel
// unexported, so the test compares by error string.
func isEdgeFormatMismatch(err error) bool {
	if err == nil {
		return false
	}
	return err == errEdgeFormatMismatch ||
		err.Error() == errEdgeFormatMismatch.Error()
}

// TestEdgeCompactV2_NumIDExtremes — pin that uint64 numIDs at both
// extremes (0 and MaxUint64) round-trip through the big-endian
// encoding without sign-extension or wraparound. The dict allocator
// in production never returns 0, but a buggy migration that did would
// otherwise crash silently here.
func TestEdgeCompactV2_NumIDExtremes(t *testing.T) {
	eng := newTestEngine(t)

	// We bypass the dict allocator and write synthetic numIDs.
	now := time.Unix(0, time.Now().UnixNano()).UTC()
	for _, pair := range []struct {
		start, end uint64
	}{
		{0, math.MaxUint64},
		{math.MaxUint64, 0},
		{1, math.MaxUint64 - 1},
	} {
		body := encodeEdgeCompactHeader(edgeFormatCompactV2, &Edge{
			Type:       "T",
			CreatedAt:  now,
			UpdatedAt:  now,
			Confidence: 1.0,
		}, pair.start, pair.end, 0)
		body = append(body, 0x00) // empty tokenized payload

		// We can't decodeEdgeBodyWithID because the dict won't know the
		// numIDs. But decodeEdgeCompactV2 returns the numIDs directly.
		decoded, gotStart, gotEnd, err := eng.decodeEdgeCompactV2("ns", body)
		require.NoError(t, err, "start=%d end=%d", pair.start, pair.end)
		assert.Equal(t, pair.start, gotStart)
		assert.Equal(t, pair.end, gotEnd)
		assert.Equal(t, "T", decoded.Type)
	}
}

// TestEdgeCompactHeader_FlagsAreLowerTwoBitsOnly — pin the lower 6
// bits of the flag byte are reserved for future use and ignored on
// decode. Setting them must not flip AutoGenerated or
// VisibilitySuppressed and must not error.
func TestEdgeCompactHeader_ReservedFlagBitsIgnored(t *testing.T) {
	eng := newTestEngine(t)

	now := time.Unix(0, time.Now().UnixNano()).UTC()
	// Build a body with only auto bit set, then forge upper bits.
	body := encodeEdgeCompactHeader(edgeFormatCompactV2, &Edge{
		Type:          "T",
		CreatedAt:     now,
		UpdatedAt:     now,
		Confidence:    1.0,
		AutoGenerated: true,
	}, 1, 2, 0)
	body[1] |= 0xfc // set the upper 6 bits
	body = append(body, 0x00)

	decoded, _, _, err := eng.decodeEdgeCompactV2("ns", body)
	require.NoError(t, err)
	assert.True(t, decoded.AutoGenerated, "auto bit must still decode true")
	assert.False(t, decoded.VisibilitySuppressed, "suppressed bit must still decode false")
}

// TestEdgeFormatMismatchSentinel_IsInstanceComparable — the migration
// code uses the sentinel error to detect already-migrated bodies. Pin
// that == comparison (and the equivalent errors.Is) work.
func TestEdgeFormatMismatchSentinel_IsInstanceComparable(t *testing.T) {
	body := make([]byte, edgeHeaderSize)
	body[0] = edgeFormatCompactV2 // V1 decoder will reject

	_, _, _, err := decodeEdgeCompactV1(body)
	require.Error(t, err)
	assert.True(t, err == errEdgeFormatMismatch || err.Error() == errEdgeFormatMismatch.Error(),
		"V1 decoder reject must surface the package sentinel (got %T: %v)", err, err)
	_ = badger.ErrTxnTooBig // silence import lint for cases where this file alone is built
}
