package storage

import (
	"encoding/binary"
	"fmt"
	"math"
	"time"

	"github.com/dgraph-io/badger/v4"
	"github.com/orneryd/nornicdb/pkg/util"
	"github.com/vmihailenco/msgpack/v5"
)

// Compact on-disk edge format.
//
// Rationale: the default gob/msgpack-serialized edge carries field names
// ("ID", "StartNode", "EndNode", "Type", "Properties", "CreatedAt",
// "UpdatedAt", "Confidence", ...) plus full 40–50-byte UUID strings for
// the IDs. On a 300k-edge graph that's ~30-40 MiB of field-name and
// string-ID overhead per body prefix.
//
// V1 (`edgeFormatCompactV1 = 0x02`):
//   - Drops Edge.ID entirely (it's the key suffix — callers reconstruct
//     it from the lookup key).
//   - Stores StartNode / EndNode as 8-byte numeric IDs backed by the
//     engine's id dictionary.
//   - Stores scalar metadata as fixed-width binary.
//   - Stores Type + Properties as msgpack with string-keyed property maps.
//
// V2 (`edgeFormatCompactV2 = 0x03`): identical framing to V1 except the
// trailing properties payload is `msgpack(map[uint64]any)` — keys are
// per-namespace dictionary IDs instead of strings.
//
// Layout (both versions):
//
//	[0]        : format byte
//	[1]        : flags (bit 0 = AutoGenerated, bit 1 = VisibilitySuppressed)
//	[2..9]     : StartNode numID (big-endian uint64)
//	[10..17]   : EndNode numID
//	[18..25]   : CreatedAt nanos (int64)
//	[26..33]   : UpdatedAt nanos (int64)
//	[34..41]   : Confidence (uint64 bit-pattern of float64)
//	[42..]     : varint(typeLen) + typeBytes
//	[...]      : msgpack(Properties)   -- map[string]any in V1, map[uint64]any in V2
//
// V1 bodies survive only inside V1→V2 migration code; the engine emits
// V2 exclusively once the storage version reaches V2.
const (
	edgeFormatCompactV1 byte = 0x02
	edgeFlagAutoGen     byte = 1 << 0
	edgeFlagSuppressed  byte = 1 << 1
)

// encodeEdgeCompactHeader writes the fixed-width prefix shared by V1 and
// V2 (everything up to and including the type bytes). Returns the buffer
// with the type written; callers append the properties payload.
func encodeEdgeCompactHeader(format byte, edge *Edge, startNum, endNum uint64, propsCap int) []byte {
	typeBytes := []byte(edge.Type)
	header := 1 + 1 + 8 + 8 + 8 + 8 + 8
	buf := make([]byte, 0, header+5+len(typeBytes)+propsCap)
	buf = append(buf, format)

	var flags byte
	if edge.AutoGenerated {
		flags |= edgeFlagAutoGen
	}
	if edge.VisibilitySuppressed {
		flags |= edgeFlagSuppressed
	}
	buf = append(buf, flags)

	var scratch [8]byte
	binary.BigEndian.PutUint64(scratch[:], startNum)
	buf = append(buf, scratch[:]...)
	binary.BigEndian.PutUint64(scratch[:], endNum)
	buf = append(buf, scratch[:]...)
	binary.BigEndian.PutUint64(scratch[:], uint64(edge.CreatedAt.UTC().UnixNano()))
	buf = append(buf, scratch[:]...)
	binary.BigEndian.PutUint64(scratch[:], uint64(edge.UpdatedAt.UTC().UnixNano()))
	buf = append(buf, scratch[:]...)
	binary.BigEndian.PutUint64(scratch[:], math.Float64bits(edge.Confidence))
	buf = append(buf, scratch[:]...)

	buf = binary.AppendUvarint(buf, uint64(len(typeBytes)))
	buf = append(buf, typeBytes...)
	return buf
}

// decodeEdgeCompactHeader is the shared parse for V1 and V2 bodies. It
// validates the leading format byte, fixed-width fields, and the type
// string, returning the parsed edge along with the offset where the
// properties payload begins. Callers slice data[offset:] and decode it
// with the codec appropriate for the version they expect.
func decodeEdgeCompactHeader(data []byte, expectedFormat byte) (*Edge, uint64, uint64, int, error) {
	if len(data) < 1 || data[0] != expectedFormat {
		return nil, 0, 0, 0, errEdgeFormatMismatch
	}
	if len(data) < 1+1+8+8+8+8+8 {
		return nil, 0, 0, 0, fmt.Errorf("compact edge truncated: %d bytes", len(data))
	}
	offset := 1
	flags := data[offset]
	offset++
	startNum := binary.BigEndian.Uint64(data[offset : offset+8])
	offset += 8
	endNum := binary.BigEndian.Uint64(data[offset : offset+8])
	offset += 8
	createdNs := int64(binary.BigEndian.Uint64(data[offset : offset+8]))
	offset += 8
	updatedNs := int64(binary.BigEndian.Uint64(data[offset : offset+8]))
	offset += 8
	confidence := math.Float64frombits(binary.BigEndian.Uint64(data[offset : offset+8]))
	offset += 8

	typeLen, n := binary.Uvarint(data[offset:])
	if n <= 0 {
		return nil, 0, 0, 0, fmt.Errorf("compact edge: invalid type length varint")
	}
	offset += n
	if offset+int(typeLen) > len(data) {
		return nil, 0, 0, 0, fmt.Errorf("compact edge: type exceeds payload")
	}
	edgeType := string(data[offset : offset+int(typeLen)])
	offset += int(typeLen)

	edge := &Edge{
		Type:                 edgeType,
		CreatedAt:            time.Unix(0, createdNs).UTC(),
		UpdatedAt:            time.Unix(0, updatedNs).UTC(),
		Confidence:           confidence,
		AutoGenerated:        flags&edgeFlagAutoGen != 0,
		VisibilitySuppressed: flags&edgeFlagSuppressed != 0,
	}
	return edge, startNum, endNum, offset, nil
}

var errEdgeFormatMismatch = fmt.Errorf("compact edge: format byte mismatch")

// decodeEdgeCompactV1 parses a V1 compact body. Used only by V1→V2
// migration code — the engine's hot path never calls this once the
// storage version is V2.
func decodeEdgeCompactV1(data []byte) (*Edge, uint64, uint64, error) {
	edge, startNum, endNum, offset, err := decodeEdgeCompactHeader(data, edgeFormatCompactV1)
	if err != nil {
		return nil, 0, 0, err
	}
	var props map[string]any
	if offset < len(data) {
		if err := util.DecodeMsgpackBytes(data[offset:], &props); err != nil {
			return nil, 0, 0, fmt.Errorf("compact edge v1: decoding properties: %w", err)
		}
	}
	edge.Properties = props
	return edge, startNum, endNum, nil
}

// decodeEdgeCompactV2 parses a V2 compact body and resolves tokenized
// property keys via the per-namespace dictionary.
func (b *BadgerEngine) decodeEdgeCompactV2(namespace string, data []byte) (*Edge, uint64, uint64, error) {
	edge, startNum, endNum, offset, err := decodeEdgeCompactHeader(data, edgeFormatCompactV2)
	if err != nil {
		return nil, 0, 0, err
	}
	var props map[string]any
	if offset < len(data) {
		props, err = b.decodeTokenizedProperties(namespace, data[offset:])
		if err != nil {
			return nil, 0, 0, fmt.Errorf("compact edge v2: %w", err)
		}
	} else {
		props = map[string]any{}
	}
	edge.Properties = props
	return edge, startNum, endNum, nil
}

// encodeEdgeCompactV1 builds a V1 body with string-keyed properties.
// Used only by tests that simulate pre-V2 stores. Production code never
// calls this.
func encodeEdgeCompactV1(edge *Edge, startNum, endNum uint64) ([]byte, error) {
	if err := validatePropertiesForStorage(edge.Properties); err != nil {
		return nil, fmt.Errorf("invalid edge properties: %w", err)
	}
	propsBytes, err := msgpack.Marshal(edge.Properties)
	if err != nil {
		return nil, fmt.Errorf("marshaling edge properties: %w", err)
	}
	buf := encodeEdgeCompactHeader(edgeFormatCompactV1, edge, startNum, endNum, len(propsBytes))
	buf = append(buf, propsBytes...)
	return buf, nil
}

// encodeEdgeCompactV2 builds a V2 body, allocating per-namespace
// property-key dictionary IDs inside the caller's txn.
func (b *BadgerEngine) encodeEdgeCompactV2(txn *badger.Txn, namespace string, edge *Edge, startNum, endNum uint64) ([]byte, error) {
	if err := validatePropertiesForStorage(edge.Properties); err != nil {
		return nil, fmt.Errorf("invalid edge properties: %w", err)
	}
	propsBytes, err := b.encodeTokenizedProperties(txn, namespace, edge.Properties)
	if err != nil {
		return nil, err
	}
	buf := encodeEdgeCompactHeader(edgeFormatCompactV2, edge, startNum, endNum, len(propsBytes))
	buf = append(buf, propsBytes...)
	return buf, nil
}

// encodeEdgeInTxn resolves (allocating if needed) endpoint numIDs via
// the id dictionary and emits a V2 compact edge body. Callers must
// supply the namespace so property-key allocation goes to the correct
// per-namespace bucket.
func (b *BadgerEngine) encodeEdgeInTxn(txn *badger.Txn, namespace string, edge *Edge) ([]byte, error) {
	startNum, err := b.idDict.resolveOrAllocateNodeNumIDInTxn(txn, edge.StartNode)
	if err != nil {
		return nil, fmt.Errorf("allocating start node numID: %w", err)
	}
	endNum, err := b.idDict.resolveOrAllocateNodeNumIDInTxn(txn, edge.EndNode)
	if err != nil {
		return nil, fmt.Errorf("allocating end node numID: %w", err)
	}
	return b.encodeEdgeCompactV2(txn, namespace, edge, startNum, endNum)
}

// decodeEdgeBody is the V2 hot-path decoder. It rejects any non-V2
// body — V2 stores have been fully rewritten by the V1→V2 migration,
// so a non-V2 body indicates corruption or a forgotten upgrade.
func (b *BadgerEngine) decodeEdgeBody(namespace string, data []byte) (*Edge, error) {
	return b.decodeEdgeBodyWithID(namespace, data, "")
}

// decodeEdgeBodyWithID is decodeEdgeBody with a caller-supplied edge
// ID, populated on the returned Edge.
func (b *BadgerEngine) decodeEdgeBodyWithID(namespace string, data []byte, id EdgeID) (*Edge, error) {
	if len(data) < 1 {
		return nil, fmt.Errorf("edge body empty")
	}
	if data[0] != edgeFormatCompactV2 {
		return nil, fmt.Errorf("edge body has unexpected format byte 0x%02x; expected V2 (0x%02x)", data[0], edgeFormatCompactV2)
	}
	edge, startNum, endNum, err := b.decodeEdgeCompactV2(namespace, data)
	if err != nil {
		return nil, err
	}
	startID, ok := b.idDict.lookupNodeIDByNum(startNum)
	if !ok {
		return nil, fmt.Errorf("compact edge: start numID %d not in dict", startNum)
	}
	endID, ok := b.idDict.lookupNodeIDByNum(endNum)
	if !ok {
		return nil, fmt.Errorf("compact edge: end numID %d not in dict", endNum)
	}
	edge.ID = id
	edge.StartNode = startID
	edge.EndNode = endID
	return edge, nil
}
