package storage

import (
	"sort"
	"testing"
	"time"

	"github.com/dgraph-io/badger/v4"
	"github.com/orneryd/nornicdb/pkg/knowledgepolicy"
	"github.com/stretchr/testify/require"
)

// v0NodeFixture is the on-disk shape of a Node before the access-state
// extraction in v1: the access fields lived on the node body itself,
// alongside the labels/properties. Every node body in a real v0 store
// matched this layout. Declared in the test file (rather than reused
// from production code) because the production Node has long since
// dropped these fields; the test is the only thing that needs to write
// them today.
type v0NodeFixture struct {
	ID           NodeID         `msgpack:"ID"`
	Labels       []string       `msgpack:"Labels"`
	Properties   map[string]any `msgpack:"Properties"`
	CreatedAt    time.Time      `msgpack:"CreatedAt"`
	UpdatedAt    time.Time      `msgpack:"UpdatedAt"`
	DecayScore   float64        `msgpack:"DecayScore"`
	LastAccessed time.Time      `msgpack:"LastAccessed"`
	AccessCount  int64          `msgpack:"AccessCount"`
}

// e2eFixtureNode bundles the data we care about preserving across the
// full migration chain so the test can assert against it post-migration
// without hard-coding values inline at every check.
type e2eFixtureNode struct {
	ID           NodeID
	Labels       []string
	Properties   map[string]any
	DecayScore   float64
	LastAccessed time.Time
	AccessCount  int64
}

// e2eFixtureEdge bundles the data we care about for an edge. The
// CreatedAt/Confidence/AutoGenerated fields exercise the NornicDB
// extensions that live in the edge body alongside the Neo4j core
// fields.
type e2eFixtureEdge struct {
	ID            EdgeID
	StartNode     NodeID
	EndNode       NodeID
	Type          string
	Properties    map[string]any
	CreatedAt     time.Time
	Confidence    float64
	AutoGenerated bool
}

func writeV0NodeFixture(t *testing.T, eng *BadgerEngine, fix e2eFixtureNode) {
	t.Helper()
	body := v0NodeFixture{
		ID:           fix.ID,
		Labels:       fix.Labels,
		Properties:   fix.Properties,
		CreatedAt:    time.Unix(1_700_000_000, 0).UTC(),
		UpdatedAt:    time.Unix(1_700_000_500, 0).UTC(),
		DecayScore:   fix.DecayScore,
		LastAccessed: fix.LastAccessed,
		AccessCount:  fix.AccessCount,
	}
	data, err := encodeValue(&body)
	require.NoError(t, err)
	require.NoError(t, eng.db.Update(func(txn *badger.Txn) error {
		return txn.Set(nodeKey(fix.ID), data)
	}))
}

func writeV0EdgeFixture(t *testing.T, eng *BadgerEngine, fix e2eFixtureEdge) {
	t.Helper()
	edge := &Edge{
		ID:            fix.ID,
		StartNode:     fix.StartNode,
		EndNode:       fix.EndNode,
		Type:          fix.Type,
		Properties:    fix.Properties,
		CreatedAt:     fix.CreatedAt,
		Confidence:    fix.Confidence,
		AutoGenerated: fix.AutoGenerated,
	}
	body, err := encodeEdge(edge)
	require.NoError(t, err)
	require.NoError(t, eng.db.Update(func(txn *badger.Txn) error {
		return txn.Set(edgeKey(fix.ID), body)
	}))
}

// TestMigrationE2E_V0ToCurrent stages a realistic v0 layout — multiple
// nodes across two namespaces with varied property types, multiple
// labels, and edges connecting them (some legacy non-compact, some
// already at v1 compact) — then opens the engine with
// AllowStorageUpgrade=true and verifies that every label, property,
// edge endpoint, type, and access-state field round-trips cleanly
// through both migration arms and the post-migration close+reopen+
// compaction step.
func TestMigrationE2E_V0ToCurrent(t *testing.T) {
	dir := t.TempDir()

	// Fixed timestamps so we can compare exact values after migration
	// instead of fuzzing on time.Now().
	t1 := time.Date(2025, 6, 1, 12, 0, 0, 0, time.UTC)
	t2 := time.Date(2025, 6, 2, 9, 30, 0, 0, time.UTC)
	t3 := time.Date(2025, 6, 3, 15, 45, 0, 0, time.UTC)

	nodeFixtures := []e2eFixtureNode{
		{
			ID:     "team-alpha:alice",
			Labels: []string{"Person", "Engineer"},
			Properties: map[string]any{
				"name":        "Alice",
				"age":         int64(34),
				"weight_kg":   72.5,
				"active":      true,
				"tags":        []any{"founder", "platform"},
				"join_year":   int64(2018),
				"description": "early hire, full-stack",
			},
			DecayScore:   0.82,
			LastAccessed: t1,
			AccessCount:  120,
		},
		{
			ID:     "team-alpha:bob",
			Labels: []string{"Person"},
			Properties: map[string]any{
				"name":     "Bob",
				"age":      int64(29),
				"location": "Berlin",
			},
			DecayScore:   0.41,
			LastAccessed: t2,
			AccessCount:  37,
		},
		{
			// No access state — v0→v1 should NOT emit AccessMeta for
			// this one. Properties should still survive.
			ID:     "team-alpha:carol",
			Labels: []string{"Person", "Designer"},
			Properties: map[string]any{
				"name": "Carol",
				"age":  int64(41),
			},
		},
		{
			// Different namespace — guards against per-namespace
			// property-key dictionary leaks during v1→v2.
			ID:     "team-beta:doc-42",
			Labels: []string{"Document", "Public"},
			Properties: map[string]any{
				"title":      "Migration Notes",
				"word_count": int64(2500),
				"published":  true,
			},
			DecayScore:   0.15,
			LastAccessed: t3,
			AccessCount:  9,
		},
		// Multi-hop chain extension: doc-42 cites cite-target, and
		// dave sits at the deepest reachable layer from alice via
		// bob → carol → doc-42 → cite-target. The chain is structured
		// to exercise both directed multi-hop traversal and a diamond
		// (alice→bob→carol and alice→carol both reach carol). Without
		// the v1→v2 secondary-index rebuild, GetOutgoingEdges returns
		// nothing and these multi-hop walks collapse to the root node
		// only — that's the regression this graph guards against.
		{
			ID:     "team-beta:cite-target",
			Labels: []string{"Document", "External"},
			Properties: map[string]any{
				"title":  "Foundational Paper",
				"author": "Knuth",
			},
		},
		{
			ID:     "team-alpha:dave",
			Labels: []string{"Person", "Reviewer"},
			Properties: map[string]any{
				"name":     "Dave",
				"location": "Madrid",
			},
		},
	}

	// Stage 1: open a fresh engine, populate via the normal write
	// path so secondary indexes (label, edge-type, edge-between)
	// land cleanly, then overwrite each node body with a v0-shaped
	// body that includes the legacy access fields, and overwrite each
	// edge body with a legacy non-compact form. Finally stamp the
	// schema version back to 0 so the next open sees a v0 store and
	// runs the full migration chain.
	{
		eng, err := NewBadgerEngineWithOptions(BadgerOptions{DataDir: dir})
		require.NoError(t, err)

		for _, fix := range nodeFixtures {
			n := &Node{
				ID:         fix.ID,
				Labels:     fix.Labels,
				Properties: fix.Properties,
			}
			_, err := eng.CreateNode(n)
			require.NoError(t, err, "CreateNode(%q)", fix.ID)
		}
		// Now overwrite every node body with a v0-shaped body so
		// migration sees the legacy access fields.
		for _, fix := range nodeFixtures {
			writeV0NodeFixture(t, eng, fix)
		}

		edgeFixtures := []e2eFixtureEdge{
			{
				ID:        "team-alpha:edge-knows-1",
				StartNode: "team-alpha:alice",
				EndNode:   "team-alpha:bob",
				Type:      "KNOWS",
				Properties: map[string]any{
					"since":    "2020-01-15",
					"strength": "close",
				},
				CreatedAt:     t1,
				Confidence:    0.95,
				AutoGenerated: false,
			},
			{
				ID:        "team-alpha:edge-mentors-1",
				StartNode: "team-alpha:alice",
				EndNode:   "team-alpha:carol",
				Type:      "MENTORS",
				Properties: map[string]any{
					"since":    "2021-09-01",
					"sessions": int64(48),
				},
				CreatedAt:     t2,
				Confidence:    1.0,
				AutoGenerated: false,
			},
			{
				// Cross-namespace edge — both endpoints live in
				// different namespaces; v1→v2 picks the start node's
				// namespace for the property dictionary.
				ID:        "team-alpha:edge-authored-1",
				StartNode: "team-alpha:alice",
				EndNode:   "team-beta:doc-42",
				Type:      "AUTHORED",
				Properties: map[string]any{
					"role": "lead",
				},
				CreatedAt:     t3,
				Confidence:    0.8,
				AutoGenerated: true,
			},
			// Chain edges so a depth-3 traversal from alice reaches
			// cite-target. Each intermediate hop must be re-emitted
			// in the numID-keyed shape by the index rebuild — if any
			// hop is missing, the BFS walk stops short.
			{
				ID:            "team-alpha:edge-follows-1",
				StartNode:     "team-alpha:bob",
				EndNode:       "team-alpha:carol",
				Type:          "FOLLOWS",
				Properties:    map[string]any{"since": "2022-03-10"},
				CreatedAt:     t1,
				Confidence:    0.9,
				AutoGenerated: false,
			},
			{
				ID:            "team-alpha:edge-reads-1",
				StartNode:     "team-alpha:carol",
				EndNode:       "team-beta:doc-42",
				Type:          "READS",
				Properties:    map[string]any{"frequency": "weekly"},
				CreatedAt:     t2,
				Confidence:    0.7,
				AutoGenerated: false,
			},
			{
				ID:            "team-beta:edge-cites-1",
				StartNode:     "team-beta:doc-42",
				EndNode:       "team-beta:cite-target",
				Type:          "CITES",
				Properties:    map[string]any{"page": int64(7)},
				CreatedAt:     t3,
				Confidence:    1.0,
				AutoGenerated: false,
			},
			// Reviewer relationship — dave reviews doc-42; gives doc-42
			// two distinct incoming edges (alice AUTHORED, dave REVIEWED)
			// so we can assert multi-incoming traversal too.
			{
				ID:            "team-alpha:edge-reviewed-1",
				StartNode:     "team-alpha:dave",
				EndNode:       "team-beta:doc-42",
				Type:          "REVIEWED",
				Properties:    map[string]any{"verdict": "accept"},
				CreatedAt:     t1,
				Confidence:    0.95,
				AutoGenerated: false,
			},
		}
		for _, fix := range edgeFixtures {
			edge := &Edge{
				ID:            fix.ID,
				StartNode:     fix.StartNode,
				EndNode:       fix.EndNode,
				Type:          fix.Type,
				Properties:    fix.Properties,
				CreatedAt:     fix.CreatedAt,
				Confidence:    fix.Confidence,
				AutoGenerated: fix.AutoGenerated,
			}
			require.NoError(t, eng.CreateEdge(edge), "CreateEdge(%q)", fix.ID)
		}
		// Overwrite each edge body with the legacy non-compact form
		// so the v1→v2 migration's pre-compact decode arm runs.
		for _, fix := range edgeFixtures {
			writeV0EdgeFixture(t, eng, fix)
		}

		require.NoError(t, eng.writeSchemaVersion(0))
		require.NoError(t, eng.Close())
	}

	// Stage 2: reopen with the upgrade flag — the full chain runs.
	eng, err := NewBadgerEngineWithOptions(BadgerOptions{
		DataDir:             dir,
		AllowStorageUpgrade: true,
	})
	require.NoError(t, err)
	t.Cleanup(func() { eng.Close() })

	// Schema version landed at current.
	require.Equal(t, storageVersionCurrent, eng.storageVersion)
	v, err := eng.readSchemaVersion()
	require.NoError(t, err)
	require.Equal(t, storageVersionCurrent, v)

	// Every node body now starts with the v2 format byte.
	require.NoError(t, eng.db.View(func(txn *badger.Txn) error {
		opts := badger.DefaultIteratorOptions
		opts.Prefix = []byte{prefixNode}
		opts.PrefetchValues = true
		it := txn.NewIterator(opts)
		defer it.Close()
		seen := 0
		for it.Rewind(); it.ValidForPrefix(opts.Prefix); it.Next() {
			val, err := it.Item().ValueCopy(nil)
			require.NoError(t, err)
			require.NotEmpty(t, val)
			require.Equal(t, byte(nodeFormatTokenizedV1), val[0],
				"node %q body did not get rewritten to v2", string(it.Item().Key()[1:]))
			seen++
		}
		require.Equal(t, len(nodeFixtures), seen)
		return nil
	}))

	// Every edge body now starts with the v2 compact format byte.
	require.NoError(t, eng.db.View(func(txn *badger.Txn) error {
		opts := badger.DefaultIteratorOptions
		opts.Prefix = []byte{prefixEdge}
		opts.PrefetchValues = true
		it := txn.NewIterator(opts)
		defer it.Close()
		seen := 0
		for it.Rewind(); it.ValidForPrefix(opts.Prefix); it.Next() {
			val, err := it.Item().ValueCopy(nil)
			require.NoError(t, err)
			require.NotEmpty(t, val)
			require.Equal(t, byte(edgeFormatCompactV2), val[0],
				"edge %q body did not get rewritten to v2", string(it.Item().Key()[1:]))
			seen++
		}
		require.Equal(t, 7, seen)
		return nil
	}))

	// Round-trip every node through the public read path. Labels and
	// properties must come back exactly as we wrote them.
	for _, fix := range nodeFixtures {
		got, err := eng.GetNode(fix.ID)
		require.NoError(t, err, "GetNode(%q)", fix.ID)
		require.NotNil(t, got, "GetNode(%q) returned nil", fix.ID)

		gotLabels := append([]string(nil), got.Labels...)
		wantLabels := append([]string(nil), fix.Labels...)
		sort.Strings(gotLabels)
		sort.Strings(wantLabels)
		require.Equal(t, wantLabels, gotLabels, "labels for %q", fix.ID)

		require.Equal(t, fix.Properties, got.Properties, "properties for %q", fix.ID)
	}

	// Round-trip the edges. Endpoints, type, and properties must
	// survive verbatim.
	expectedEdges := map[EdgeID]e2eFixtureEdge{
		"team-alpha:edge-knows-1": {
			StartNode: "team-alpha:alice",
			EndNode:   "team-alpha:bob",
			Type:      "KNOWS",
			Properties: map[string]any{
				"since":    "2020-01-15",
				"strength": "close",
			},
		},
		"team-alpha:edge-mentors-1": {
			StartNode: "team-alpha:alice",
			EndNode:   "team-alpha:carol",
			Type:      "MENTORS",
			Properties: map[string]any{
				"since":    "2021-09-01",
				"sessions": int64(48),
			},
		},
		"team-alpha:edge-authored-1": {
			StartNode: "team-alpha:alice",
			EndNode:   "team-beta:doc-42",
			Type:      "AUTHORED",
			Properties: map[string]any{
				"role": "lead",
			},
		},
		"team-alpha:edge-follows-1": {
			StartNode: "team-alpha:bob",
			EndNode:   "team-alpha:carol",
			Type:      "FOLLOWS",
			Properties: map[string]any{
				"since": "2022-03-10",
			},
		},
		"team-alpha:edge-reads-1": {
			StartNode: "team-alpha:carol",
			EndNode:   "team-beta:doc-42",
			Type:      "READS",
			Properties: map[string]any{
				"frequency": "weekly",
			},
		},
		"team-beta:edge-cites-1": {
			StartNode: "team-beta:doc-42",
			EndNode:   "team-beta:cite-target",
			Type:      "CITES",
			Properties: map[string]any{
				"page": int64(7),
			},
		},
		"team-alpha:edge-reviewed-1": {
			StartNode: "team-alpha:dave",
			EndNode:   "team-beta:doc-42",
			Type:      "REVIEWED",
			Properties: map[string]any{
				"verdict": "accept",
			},
		},
	}
	for id, want := range expectedEdges {
		got, err := eng.GetEdge(id)
		require.NoError(t, err, "GetEdge(%q)", id)
		require.NotNil(t, got, "GetEdge(%q) returned nil", id)
		require.Equal(t, want.StartNode, got.StartNode, "start node for %q", id)
		require.Equal(t, want.EndNode, got.EndNode, "end node for %q", id)
		require.Equal(t, want.Type, got.Type, "type for %q", id)
		require.Equal(t, want.Properties, got.Properties, "properties for %q", id)
	}

	// Label-index queries: every node should be findable by every
	// label it claims, since the migration recomputes label indexes
	// off the rewritten v2 bodies.
	labelExpect := map[string][]NodeID{
		"Person":   {"team-alpha:alice", "team-alpha:bob", "team-alpha:carol", "team-alpha:dave"},
		"Engineer": {"team-alpha:alice"},
		"Designer": {"team-alpha:carol"},
		"Reviewer": {"team-alpha:dave"},
		"Document": {"team-beta:doc-42", "team-beta:cite-target"},
		"Public":   {"team-beta:doc-42"},
		"External": {"team-beta:cite-target"},
	}
	for label, wantIDs := range labelExpect {
		nodes, err := eng.GetNodesByLabel(label)
		require.NoError(t, err, "GetNodesByLabel(%q)", label)
		gotIDs := make([]NodeID, 0, len(nodes))
		for _, n := range nodes {
			gotIDs = append(gotIDs, n.ID)
		}
		sort.Slice(gotIDs, func(i, j int) bool { return gotIDs[i] < gotIDs[j] })
		sort.Slice(wantIDs, func(i, j int) bool { return wantIDs[i] < wantIDs[j] })
		require.Equal(t, wantIDs, gotIDs, "label %q membership", label)
	}

	// Edge-type-index queries: each edge type returns the edges we
	// staged.
	for edgeType, wantID := range map[string]EdgeID{
		"KNOWS":    "team-alpha:edge-knows-1",
		"MENTORS":  "team-alpha:edge-mentors-1",
		"AUTHORED": "team-alpha:edge-authored-1",
		"FOLLOWS":  "team-alpha:edge-follows-1",
		"READS":    "team-alpha:edge-reads-1",
		"CITES":    "team-beta:edge-cites-1",
		"REVIEWED": "team-alpha:edge-reviewed-1",
	} {
		edges, err := eng.GetEdgesByType(edgeType)
		require.NoError(t, err, "GetEdgesByType(%q)", edgeType)
		require.Len(t, edges, 1, "edges of type %q", edgeType)
		require.Equal(t, wantID, edges[0].ID)
	}

	// Connection traversal post-migration: outgoing, incoming, and
	// edges-between must all agree with the staged graph. These hit
	// distinct indexes (prefixOutgoingIndex, prefixIncomingIndex,
	// prefixEdgeBetweenIndex / prefixEdgeBetweenHead) — they're all
	// lookup tables that store numID-encoded references to bodies, so
	// they have to survive the v1→v2 body rewrite + the post-migration
	// reopen and edge-between backfill.

	// extractIDs is just sugar so the assertions below stay terse.
	extractIDs := func(edges []*Edge) []string {
		out := make([]string, 0, len(edges))
		for _, e := range edges {
			out = append(out, string(e.ID))
		}
		sort.Strings(out)
		return out
	}

	// Outgoing edges: alice has 3, bob has 1, carol has 1, doc-42 has 1,
	// dave has 1, cite-target has 0.
	outgoingExpect := map[NodeID][]string{
		"team-alpha:alice": {
			"team-alpha:edge-authored-1",
			"team-alpha:edge-knows-1",
			"team-alpha:edge-mentors-1",
		},
		"team-alpha:bob":        {"team-alpha:edge-follows-1"},
		"team-alpha:carol":      {"team-alpha:edge-reads-1"},
		"team-beta:doc-42":      {"team-beta:edge-cites-1"},
		"team-alpha:dave":       {"team-alpha:edge-reviewed-1"},
		"team-beta:cite-target": {},
	}
	for nodeID, want := range outgoingExpect {
		got, err := eng.GetOutgoingEdges(nodeID)
		require.NoError(t, err, "GetOutgoingEdges(%q)", nodeID)
		require.Equal(t, want, extractIDs(got), "outgoing edges for %q", nodeID)
	}

	// Incoming edges. Note doc-42 has TWO incoming edges (AUTHORED
	// from alice, REVIEWED from dave) — exercises a multi-incoming
	// scan through the rebuilt incoming index.
	incomingExpect := map[NodeID][]string{
		"team-alpha:alice": {},
		"team-alpha:bob":   {"team-alpha:edge-knows-1"},
		"team-alpha:carol": {
			"team-alpha:edge-follows-1",
			"team-alpha:edge-mentors-1",
		},
		"team-beta:doc-42": {
			"team-alpha:edge-authored-1",
			"team-alpha:edge-reads-1",
			"team-alpha:edge-reviewed-1",
		},
		"team-beta:cite-target": {"team-beta:edge-cites-1"},
		"team-alpha:dave":       {},
	}
	for nodeID, want := range incomingExpect {
		got, err := eng.GetIncomingEdges(nodeID)
		require.NoError(t, err, "GetIncomingEdges(%q)", nodeID)
		require.Equal(t, want, extractIDs(got), "incoming edges for %q", nodeID)
	}

	// edges-between covers every connected and one disconnected pair.
	// Each connected pair must return the staged edge with its body
	// fully decoded (Type, Properties) so we know the index resolved
	// to a v2 body, not a stale v1 record.
	type betweenCase struct {
		start, end NodeID
		wantIDs    []string
	}
	betweenCases := []betweenCase{
		{"team-alpha:alice", "team-alpha:bob", []string{"team-alpha:edge-knows-1"}},
		{"team-alpha:alice", "team-alpha:carol", []string{"team-alpha:edge-mentors-1"}},
		{"team-alpha:alice", "team-beta:doc-42", []string{"team-alpha:edge-authored-1"}},
		{"team-alpha:bob", "team-alpha:carol", []string{"team-alpha:edge-follows-1"}},
		{"team-alpha:carol", "team-beta:doc-42", []string{"team-alpha:edge-reads-1"}},
		{"team-beta:doc-42", "team-beta:cite-target", []string{"team-beta:edge-cites-1"}},
		{"team-alpha:dave", "team-beta:doc-42", []string{"team-alpha:edge-reviewed-1"}},
		{"team-alpha:carol", "team-alpha:alice", []string{}},      // wrong direction
		{"team-beta:cite-target", "team-alpha:alice", []string{}}, // unconnected
	}
	for _, tc := range betweenCases {
		got, err := eng.GetEdgesBetween(tc.start, tc.end)
		require.NoError(t, err, "GetEdgesBetween(%q, %q)", tc.start, tc.end)
		require.Equal(t, tc.wantIDs, extractIDs(got),
			"edges-between %q→%q", tc.start, tc.end)
	}

	// edge-between-head index — the fast single-edge lookup. Each
	// triple maps to the edge we staged; bodies must round-trip Type
	// and Properties through the v2 codec.
	type headCase struct {
		start, end NodeID
		edgeType   string
		wantID     EdgeID
		wantProps  map[string]any
	}
	headCases := []headCase{
		{
			"team-alpha:alice", "team-alpha:bob", "KNOWS",
			"team-alpha:edge-knows-1",
			map[string]any{"since": "2020-01-15", "strength": "close"},
		},
		{
			"team-alpha:alice", "team-alpha:carol", "MENTORS",
			"team-alpha:edge-mentors-1",
			map[string]any{"since": "2021-09-01", "sessions": int64(48)},
		},
		{
			"team-alpha:alice", "team-beta:doc-42", "AUTHORED",
			"team-alpha:edge-authored-1",
			map[string]any{"role": "lead"},
		},
		{
			"team-alpha:bob", "team-alpha:carol", "FOLLOWS",
			"team-alpha:edge-follows-1",
			map[string]any{"since": "2022-03-10"},
		},
		{
			"team-alpha:carol", "team-beta:doc-42", "READS",
			"team-alpha:edge-reads-1",
			map[string]any{"frequency": "weekly"},
		},
		{
			"team-beta:doc-42", "team-beta:cite-target", "CITES",
			"team-beta:edge-cites-1",
			map[string]any{"page": int64(7)},
		},
		{
			"team-alpha:dave", "team-beta:doc-42", "REVIEWED",
			"team-alpha:edge-reviewed-1",
			map[string]any{"verdict": "accept"},
		},
	}
	for _, tc := range headCases {
		got := eng.GetEdgeBetween(tc.start, tc.end, tc.edgeType)
		require.NotNil(t, got, "GetEdgeBetween(%q, %q, %q)", tc.start, tc.end, tc.edgeType)
		require.Equal(t, tc.wantID, got.ID)
		require.Equal(t, tc.start, got.StartNode)
		require.Equal(t, tc.end, got.EndNode)
		require.Equal(t, tc.edgeType, got.Type)
		require.Equal(t, tc.wantProps, got.Properties)
	}

	// Negative head lookups — wrong type or unconnected pair must
	// return nil, not the wrong edge.
	require.Nil(t, eng.GetEdgeBetween("team-alpha:alice", "team-alpha:bob", "MENTORS"),
		"alice→bob has KNOWS, not MENTORS")
	require.Nil(t, eng.GetEdgeBetween("team-alpha:bob", "team-alpha:alice", "KNOWS"),
		"directed edge: bob→alice should not match alice→bob KNOWS")

	// Access metadata: v0→v1 lifted DecayScore/AccessCount/
	// LastAccessed onto AccessMeta records, but ONLY for nodes that
	// had non-zero access state. Carol had none — no entry expected.
	for _, fix := range nodeFixtures {
		meta, err := eng.GetAccessMeta(string(fix.ID))
		require.NoError(t, err, "GetAccessMeta(%q)", fix.ID)
		if fix.AccessCount == 0 && fix.DecayScore == 0 && fix.LastAccessed.IsZero() {
			require.Nil(t, meta, "expected no AccessMeta for %q", fix.ID)
			continue
		}
		require.NotNil(t, meta, "expected AccessMeta for %q", fix.ID)
		require.Equal(t, knowledgepolicy.ScopeNode, meta.TargetScope)
		require.Equal(t, fix.AccessCount, meta.Fixed.AccessCount, "access count for %q", fix.ID)
		require.Equal(t, fix.LastAccessed.UnixNano(), meta.Fixed.LastAccessedAt, "last-accessed for %q", fix.ID)
	}

	// Multi-hop traversal regression (the bug this whole change is
	// fixing). The graph as staged:
	//
	//   alice -KNOWS-> bob -FOLLOWS-> carol -READS-> doc-42 -CITES-> cite-target
	//   alice -MENTORS-> carol -READS-> doc-42 -CITES-> cite-target
	//   alice -AUTHORED-> doc-42 -CITES-> cite-target
	//   dave  -REVIEWED-> doc-42 -CITES-> cite-target
	//
	// A correct migration leaves every hop intact. Before the
	// secondary-index rebuild was added, the very first hop returned
	// no outgoing edges and BFS terminated at the root — the graph
	// explorer in the user-visible UI showed "1 nodes, 0 edges"
	// regardless of the actual data. The walks below would all return
	// {root only}, so any assertion of len > 1 is a regression catch.
	bfsReachable := func(start NodeID, depth int) map[NodeID]struct{} {
		visited := map[NodeID]struct{}{start: {}}
		frontier := []NodeID{start}
		for hop := 0; hop < depth; hop++ {
			var next []NodeID
			for _, n := range frontier {
				out, err := eng.GetOutgoingEdges(n)
				require.NoError(t, err, "BFS GetOutgoingEdges(%q)", n)
				for _, e := range out {
					if _, ok := visited[e.EndNode]; ok {
						continue
					}
					visited[e.EndNode] = struct{}{}
					next = append(next, e.EndNode)
				}
			}
			frontier = next
		}
		return visited
	}

	// Depth-1 from alice: alice + her three direct neighbors.
	depth1 := bfsReachable("team-alpha:alice", 1)
	require.Contains(t, depth1, NodeID("team-alpha:alice"))
	require.Contains(t, depth1, NodeID("team-alpha:bob"))
	require.Contains(t, depth1, NodeID("team-alpha:carol"))
	require.Contains(t, depth1, NodeID("team-beta:doc-42"))
	require.Len(t, depth1, 4, "depth-1 reachable set size")

	// Depth-2 from alice picks up cite-target (via doc-42) — carol
	// was already reachable at depth 1 (alice→carol direct), so the
	// only NEW node at depth 2 is cite-target. The diamond (alice→bob
	// →carol AND alice→carol both reach carol) means carol must not
	// double-count.
	depth2 := bfsReachable("team-alpha:alice", 2)
	require.Contains(t, depth2, NodeID("team-beta:cite-target"))
	require.Len(t, depth2, 5, "depth-2 reachable set size (alice + 3 direct + cite-target)")

	// Depth-3 from alice should not add any new nodes — the graph's
	// longest forward path from alice is alice→bob→carol→doc-42 (3
	// hops) but doc-42 is already reachable at depth 1, and from
	// doc-42 only cite-target is new which was already picked up at
	// depth 2.
	depth3 := bfsReachable("team-alpha:alice", 3)
	require.Equal(t, len(depth2), len(depth3),
		"depth-3 reachable set should not grow past depth-2")

	// dave is a separate root that shares doc-42's downstream
	// subtree. From dave we reach doc-42 at depth 1 and cite-target
	// at depth 2. The fact that dave shares cite-target with alice
	// confirms the rebuilt outgoing index is consistent across roots.
	daveDepth2 := bfsReachable("team-alpha:dave", 2)
	require.Contains(t, daveDepth2, NodeID("team-beta:doc-42"))
	require.Contains(t, daveDepth2, NodeID("team-beta:cite-target"))
	require.Len(t, daveDepth2, 3, "dave reaches doc-42 + cite-target at depth 2")

	// Reverse traversal: BFS over incoming edges. From cite-target,
	// every other node should be reachable within 4 hops (dave is
	// the deepest predecessor: dave→doc-42→...→cite-target is 2 hops
	// reverse, but alice→bob→carol→doc-42→cite-target is 4 hops
	// reverse so ALL eight nodes are reachable at depth 4).
	bfsReverseReachable := func(start NodeID, depth int) map[NodeID]struct{} {
		visited := map[NodeID]struct{}{start: {}}
		frontier := []NodeID{start}
		for hop := 0; hop < depth; hop++ {
			var next []NodeID
			for _, n := range frontier {
				in, err := eng.GetIncomingEdges(n)
				require.NoError(t, err, "BFS GetIncomingEdges(%q)", n)
				for _, e := range in {
					if _, ok := visited[e.StartNode]; ok {
						continue
					}
					visited[e.StartNode] = struct{}{}
					next = append(next, e.StartNode)
				}
			}
			frontier = next
		}
		return visited
	}
	reverseAll := bfsReverseReachable("team-beta:cite-target", 4)
	for _, want := range []NodeID{
		"team-alpha:alice",
		"team-alpha:bob",
		"team-alpha:carol",
		"team-alpha:dave",
		"team-beta:doc-42",
		"team-beta:cite-target",
	} {
		require.Contains(t, reverseAll, want,
			"reverse BFS from cite-target missed %q", want)
	}

	// Node/edge counts match the fixtures.
	nodeCount, err := eng.NodeCount()
	require.NoError(t, err)
	require.Equal(t, int64(len(nodeFixtures)), nodeCount)

	edgeCount, err := eng.EdgeCount()
	require.NoError(t, err)
	require.Equal(t, int64(7), edgeCount)
}

// TestMigrationE2E_MVCCAsOfReadsSurvive stages a node with three
// distinct historical versions plus an edge with two versions, runs
// the full migration, then asserts every as-of read still resolves
// the right body.
//
// The migration's body-rewrite pass walks prefixNode and prefixEdge
// — it does NOT touch prefixMVCCNode/prefixMVCCEdge (where archived
// versions live) or prefixMVCCNodeHead. If the migration accidentally
// invalidates those records, every historical read collapses and
// time-travel queries silently return the wrong version. This test
// is the regression guard for that.
func TestMigrationE2E_MVCCAsOfReadsSurvive(t *testing.T) {
	dir := t.TempDir()

	nodeID := NodeID("history:hero")
	edgeID := EdgeID("history:edge-1")
	otherID := NodeID("history:sidekick")

	// Three logical "as-of" timestamps for hero. We use real
	// AppendNodeVersion + UpdateNodeCurrentHead so we can pin the
	// MVCC commit timestamps deterministically — natural UpdateNode
	// calls allocate from time.Now() which would race the test.
	v1 := MVCCVersion{CommitTimestamp: time.Date(2024, 1, 1, 0, 0, 0, 0, time.UTC), CommitSequence: 1}
	v2 := MVCCVersion{CommitTimestamp: time.Date(2024, 6, 1, 0, 0, 0, 0, time.UTC), CommitSequence: 2}
	v3 := MVCCVersion{CommitTimestamp: time.Date(2024, 12, 1, 0, 0, 0, 0, time.UTC), CommitSequence: 3}

	// Two snapshots for the edge so we can verify both edge MVCC and
	// node MVCC paths post-migration.
	ev1 := MVCCVersion{CommitTimestamp: time.Date(2024, 2, 1, 0, 0, 0, 0, time.UTC), CommitSequence: 10}
	ev2 := MVCCVersion{CommitTimestamp: time.Date(2024, 8, 1, 0, 0, 0, 0, time.UTC), CommitSequence: 11}

	// Stage 1: build the v0 store with a node that has three
	// historical versions and an edge that has two. Force the schema
	// version back to 0 at the end so the next open runs the chain.
	{
		eng, err := NewBadgerEngineWithOptions(BadgerOptions{DataDir: dir})
		require.NoError(t, err)

		// CreateNode for hero with the FINAL state — the primary key
		// must reflect the latest snapshot so post-migration
		// GetNodeLatestVisible (which reads the primary key) returns
		// FinalForm. Historical versions are appended below.
		_, err = eng.CreateNode(&Node{
			ID:     nodeID,
			Labels: []string{"Hero", "MaxLevel"},
			Properties: map[string]any{
				"name": "FinalForm",
				"hp":   int64(500),
			},
		})
		require.NoError(t, err)

		// CreateNode for sidekick so the edge has a real endpoint.
		_, err = eng.CreateNode(&Node{
			ID:         otherID,
			Labels:     []string{"Sidekick"},
			Properties: map[string]any{"name": "Robin"},
		})
		require.NoError(t, err)

		// Append three historical versions of hero. The bodies
		// capture distinct property snapshots so as-of reads can be
		// distinguished.
		require.NoError(t, eng.AppendNodeVersion(&Node{
			ID:     nodeID,
			Labels: []string{"Hero"},
			Properties: map[string]any{
				"name": "Origin",
				"hp":   int64(100),
			},
		}, v1))
		require.NoError(t, eng.AppendNodeVersion(&Node{
			ID:     nodeID,
			Labels: []string{"Hero", "LevelUp"},
			Properties: map[string]any{
				"name": "MidGame",
				"hp":   int64(180),
			},
		}, v2))
		require.NoError(t, eng.AppendNodeVersion(&Node{
			ID:     nodeID,
			Labels: []string{"Hero", "MaxLevel"},
			Properties: map[string]any{
				"name": "FinalForm",
				"hp":   int64(500),
			},
		}, v3))
		// Pin the head to v3 with FloorVersion=v1 so as-of reads
		// going back to the oldest historical snapshot don't trip
		// the floor-version-too-old guard. AppendNodeVersion lifts
		// the head's Version to its arg but leaves the floor at the
		// CreateNode-time value, which would be ~time.Now() and
		// reject any read older than that.
		require.NoError(t, eng.db.Update(func(txn *badger.Txn) error {
			return eng.writeNodeMVCCHeadWithFloorInTxn(txn, nodeID, v3, false, v1)
		}))

		// Edge: create with FINAL state, then append historical
		// versions. Same reasoning as the node above — the primary
		// edge key holds the latest snapshot post-migration.
		require.NoError(t, eng.CreateEdge(&Edge{
			ID:        edgeID,
			StartNode: nodeID,
			EndNode:   otherID,
			Type:      "PROTECTS",
			Properties: map[string]any{
				"loyalty": "max",
			},
		}))
		require.NoError(t, eng.AppendEdgeVersion(&Edge{
			ID:        edgeID,
			StartNode: nodeID,
			EndNode:   otherID,
			Type:      "PROTECTS",
			Properties: map[string]any{
				"loyalty": "low",
			},
		}, ev1))
		require.NoError(t, eng.AppendEdgeVersion(&Edge{
			ID:        edgeID,
			StartNode: nodeID,
			EndNode:   otherID,
			Type:      "PROTECTS",
			Properties: map[string]any{
				"loyalty": "max",
			},
		}, ev2))
		// Same floor adjustment as the node head — pin the floor
		// back to the oldest historical version so as-of reads of
		// ev1 succeed.
		require.NoError(t, eng.db.Update(func(txn *badger.Txn) error {
			return eng.writeEdgeMVCCHeadWithFloorInTxn(txn, edgeID, ev2, false, ev1)
		}))

		require.NoError(t, eng.writeSchemaVersion(0))
		require.NoError(t, eng.Close())
	}

	// Stage 2: reopen with the upgrade flag — full chain runs.
	eng, err := NewBadgerEngineWithOptions(BadgerOptions{
		DataDir:             dir,
		AllowStorageUpgrade: true,
	})
	require.NoError(t, err)
	t.Cleanup(func() { eng.Close() })
	require.Equal(t, storageVersionCurrent, eng.storageVersion)

	// Latest still resolves via the v2-rewritten primary key.
	latest, err := eng.GetNodeLatestVisible(nodeID)
	require.NoError(t, err)
	require.NotNil(t, latest)
	require.Equal(t, "FinalForm", latest.Properties["name"])
	require.Equal(t, int64(500), latest.Properties["hp"])
	gotLabels := append([]string(nil), latest.Labels...)
	sort.Strings(gotLabels)
	require.Equal(t, []string{"Hero", "MaxLevel"}, gotLabels)

	// As-of v1: oldest snapshot (Origin / 100 hp).
	atV1, err := eng.GetNodeVisibleAt(nodeID, v1)
	require.NoError(t, err)
	require.NotNil(t, atV1)
	require.Equal(t, "Origin", atV1.Properties["name"])
	require.Equal(t, int64(100), atV1.Properties["hp"])
	require.Equal(t, []string{"Hero"}, atV1.Labels)

	// As-of v2: middle snapshot (MidGame / 180 hp / LevelUp label).
	atV2, err := eng.GetNodeVisibleAt(nodeID, v2)
	require.NoError(t, err)
	require.NotNil(t, atV2)
	require.Equal(t, "MidGame", atV2.Properties["name"])
	require.Equal(t, int64(180), atV2.Properties["hp"])
	gotLabels = append([]string(nil), atV2.Labels...)
	sort.Strings(gotLabels)
	require.Equal(t, []string{"Hero", "LevelUp"}, gotLabels)

	// As-of v3: newest snapshot. Should match latest.
	atV3, err := eng.GetNodeVisibleAt(nodeID, v3)
	require.NoError(t, err)
	require.NotNil(t, atV3)
	require.Equal(t, "FinalForm", atV3.Properties["name"])
	require.Equal(t, int64(500), atV3.Properties["hp"])

	// As-of strictly between v1 and v2: must resolve to v1 (the
	// at-or-before semantics of MVCC reads). Confirms the migration
	// preserved version ordering.
	between := MVCCVersion{
		CommitTimestamp: time.Date(2024, 3, 15, 0, 0, 0, 0, time.UTC),
		CommitSequence:  100,
	}
	atBetween, err := eng.GetNodeVisibleAt(nodeID, between)
	require.NoError(t, err)
	require.NotNil(t, atBetween)
	require.Equal(t, "Origin", atBetween.Properties["name"], "between v1 and v2 must resolve to v1")

	// Edge as-of reads.
	edgeAtEv1, err := eng.GetEdgeVisibleAt(edgeID, ev1)
	require.NoError(t, err)
	require.NotNil(t, edgeAtEv1)
	require.Equal(t, "low", edgeAtEv1.Properties["loyalty"])
	require.Equal(t, "PROTECTS", edgeAtEv1.Type)
	require.Equal(t, nodeID, edgeAtEv1.StartNode)
	require.Equal(t, otherID, edgeAtEv1.EndNode)

	edgeAtEv2, err := eng.GetEdgeVisibleAt(edgeID, ev2)
	require.NoError(t, err)
	require.NotNil(t, edgeAtEv2)
	require.Equal(t, "max", edgeAtEv2.Properties["loyalty"])

	// Latest edge resolves via the rewritten v2 primary body. Latest
	// hop also exercises the rebuilt outgoing/incoming/edge-type
	// indexes — without those, GetEdgesByType/GetOutgoingEdges fail
	// silently, but GetEdgeLatestVisible reads the primary key and
	// would still work; this is just a sanity check.
	edgeLatest, err := eng.GetEdgeLatestVisible(edgeID)
	require.NoError(t, err)
	require.NotNil(t, edgeLatest)
	require.Equal(t, "max", edgeLatest.Properties["loyalty"])

	// Head versions and floors survived the migration so the as-of
	// code paths see the correct floor/current bookkeeping.
	headNode, err := eng.GetNodeCurrentHead(nodeID)
	require.NoError(t, err)
	require.Equal(t, 0, headNode.Version.Compare(v3),
		"head version after migration must equal v3, got %v", headNode.Version)
	require.Equal(t, 0, headNode.FloorVersion.Compare(v1),
		"head floor after migration must equal v1, got %v", headNode.FloorVersion)
	require.False(t, headNode.Tombstoned)

	headEdge, err := eng.GetEdgeCurrentHead(edgeID)
	require.NoError(t, err)
	require.Equal(t, 0, headEdge.Version.Compare(ev2),
		"edge head version after migration must equal ev2, got %v", headEdge.Version)
	require.Equal(t, 0, headEdge.FloorVersion.Compare(ev1),
		"edge floor after migration must equal ev1, got %v", headEdge.FloorVersion)
	require.False(t, headEdge.Tombstoned)
}
