package storage

import (
	"sort"
	"testing"
	"time"

	"github.com/dgraph-io/badger/v4"
	"github.com/orneryd/nornicdb/pkg/knowledgepolicy"
	"github.com/stretchr/testify/require"
)

// v0NodeFixture is the on-disk shape of a Node before the access-state
// extraction in v1: the access fields lived on the node body itself,
// alongside the labels/properties. Every node body in a real v0 store
// matched this layout. Declared in the test file (rather than reused
// from production code) because the production Node has long since
// dropped these fields; the test is the only thing that needs to write
// them today.
type v0NodeFixture struct {
	ID           NodeID         `msgpack:"ID"`
	Labels       []string       `msgpack:"Labels"`
	Properties   map[string]any `msgpack:"Properties"`
	CreatedAt    time.Time      `msgpack:"CreatedAt"`
	UpdatedAt    time.Time      `msgpack:"UpdatedAt"`
	DecayScore   float64        `msgpack:"DecayScore"`
	LastAccessed time.Time      `msgpack:"LastAccessed"`
	AccessCount  int64          `msgpack:"AccessCount"`
}

// e2eFixtureNode bundles the data we care about preserving across the
// full migration chain so the test can assert against it post-migration
// without hard-coding values inline at every check.
type e2eFixtureNode struct {
	ID           NodeID
	Labels       []string
	Properties   map[string]any
	DecayScore   float64
	LastAccessed time.Time
	AccessCount  int64
}

// e2eFixtureEdge bundles the data we care about for an edge. The
// CreatedAt/Confidence/AutoGenerated fields exercise the NornicDB
// extensions that live in the edge body alongside the Neo4j core
// fields.
type e2eFixtureEdge struct {
	ID            EdgeID
	StartNode     NodeID
	EndNode       NodeID
	Type          string
	Properties    map[string]any
	CreatedAt     time.Time
	Confidence    float64
	AutoGenerated bool
}

func writeV0NodeFixture(t *testing.T, eng *BadgerEngine, fix e2eFixtureNode) {
	t.Helper()
	body := v0NodeFixture{
		ID:           fix.ID,
		Labels:       fix.Labels,
		Properties:   fix.Properties,
		CreatedAt:    time.Unix(1_700_000_000, 0).UTC(),
		UpdatedAt:    time.Unix(1_700_000_500, 0).UTC(),
		DecayScore:   fix.DecayScore,
		LastAccessed: fix.LastAccessed,
		AccessCount:  fix.AccessCount,
	}
	data, err := encodeValue(&body)
	require.NoError(t, err)
	require.NoError(t, eng.db.Update(func(txn *badger.Txn) error {
		return txn.Set(nodeKey(fix.ID), data)
	}))
}

func writeV0EdgeFixture(t *testing.T, eng *BadgerEngine, fix e2eFixtureEdge) {
	t.Helper()
	edge := &Edge{
		ID:            fix.ID,
		StartNode:     fix.StartNode,
		EndNode:       fix.EndNode,
		Type:          fix.Type,
		Properties:    fix.Properties,
		CreatedAt:     fix.CreatedAt,
		Confidence:    fix.Confidence,
		AutoGenerated: fix.AutoGenerated,
	}
	body, err := encodeEdge(edge)
	require.NoError(t, err)
	require.NoError(t, eng.db.Update(func(txn *badger.Txn) error {
		return txn.Set(edgeKey(fix.ID), body)
	}))
}

// TestMigrationE2E_V0ToCurrent stages a realistic v0 layout — multiple
// nodes across two namespaces with varied property types, multiple
// labels, and edges connecting them (some legacy non-compact, some
// already at v1 compact) — then opens the engine with
// AllowStorageUpgrade=true and verifies that every label, property,
// edge endpoint, type, and access-state field round-trips cleanly
// through both migration arms and the post-migration close+reopen+
// compaction step.
func TestMigrationE2E_V0ToCurrent(t *testing.T) {
	dir := t.TempDir()

	// Fixed timestamps so we can compare exact values after migration
	// instead of fuzzing on time.Now().
	t1 := time.Date(2025, 6, 1, 12, 0, 0, 0, time.UTC)
	t2 := time.Date(2025, 6, 2, 9, 30, 0, 0, time.UTC)
	t3 := time.Date(2025, 6, 3, 15, 45, 0, 0, time.UTC)

	nodeFixtures := []e2eFixtureNode{
		{
			ID:     "team-alpha:alice",
			Labels: []string{"Person", "Engineer"},
			Properties: map[string]any{
				"name":        "Alice",
				"age":         int64(34),
				"weight_kg":   72.5,
				"active":      true,
				"tags":        []any{"founder", "platform"},
				"join_year":   int64(2018),
				"description": "early hire, full-stack",
			},
			DecayScore:   0.82,
			LastAccessed: t1,
			AccessCount:  120,
		},
		{
			ID:     "team-alpha:bob",
			Labels: []string{"Person"},
			Properties: map[string]any{
				"name":     "Bob",
				"age":      int64(29),
				"location": "Berlin",
			},
			DecayScore:   0.41,
			LastAccessed: t2,
			AccessCount:  37,
		},
		{
			// No access state — v0→v1 should NOT emit AccessMeta for
			// this one. Properties should still survive.
			ID:     "team-alpha:carol",
			Labels: []string{"Person", "Designer"},
			Properties: map[string]any{
				"name": "Carol",
				"age":  int64(41),
			},
		},
		{
			// Different namespace — guards against per-namespace
			// property-key dictionary leaks during v1→v2.
			ID:     "team-beta:doc-42",
			Labels: []string{"Document", "Public"},
			Properties: map[string]any{
				"title":      "Migration Notes",
				"word_count": int64(2500),
				"published":  true,
			},
			DecayScore:   0.15,
			LastAccessed: t3,
			AccessCount:  9,
		},
	}

	// Stage 1: open a fresh engine, populate via the normal write
	// path so secondary indexes (label, edge-type, edge-between)
	// land cleanly, then overwrite each node body with a v0-shaped
	// body that includes the legacy access fields, and overwrite each
	// edge body with a legacy non-compact form. Finally stamp the
	// schema version back to 0 so the next open sees a v0 store and
	// runs the full migration chain.
	{
		eng, err := NewBadgerEngineWithOptions(BadgerOptions{DataDir: dir})
		require.NoError(t, err)

		for _, fix := range nodeFixtures {
			n := &Node{
				ID:         fix.ID,
				Labels:     fix.Labels,
				Properties: fix.Properties,
			}
			_, err := eng.CreateNode(n)
			require.NoError(t, err, "CreateNode(%q)", fix.ID)
		}
		// Now overwrite every node body with a v0-shaped body so
		// migration sees the legacy access fields.
		for _, fix := range nodeFixtures {
			writeV0NodeFixture(t, eng, fix)
		}

		edgeFixtures := []e2eFixtureEdge{
			{
				ID:        "team-alpha:edge-knows-1",
				StartNode: "team-alpha:alice",
				EndNode:   "team-alpha:bob",
				Type:      "KNOWS",
				Properties: map[string]any{
					"since":    "2020-01-15",
					"strength": "close",
				},
				CreatedAt:     t1,
				Confidence:    0.95,
				AutoGenerated: false,
			},
			{
				ID:        "team-alpha:edge-mentors-1",
				StartNode: "team-alpha:alice",
				EndNode:   "team-alpha:carol",
				Type:      "MENTORS",
				Properties: map[string]any{
					"since":    "2021-09-01",
					"sessions": int64(48),
				},
				CreatedAt:     t2,
				Confidence:    1.0,
				AutoGenerated: false,
			},
			{
				// Cross-namespace edge — both endpoints live in
				// different namespaces; v1→v2 picks the start node's
				// namespace for the property dictionary.
				ID:        "team-alpha:edge-authored-1",
				StartNode: "team-alpha:alice",
				EndNode:   "team-beta:doc-42",
				Type:      "AUTHORED",
				Properties: map[string]any{
					"role": "lead",
				},
				CreatedAt:     t3,
				Confidence:    0.8,
				AutoGenerated: true,
			},
		}
		for _, fix := range edgeFixtures {
			edge := &Edge{
				ID:            fix.ID,
				StartNode:     fix.StartNode,
				EndNode:       fix.EndNode,
				Type:          fix.Type,
				Properties:    fix.Properties,
				CreatedAt:     fix.CreatedAt,
				Confidence:    fix.Confidence,
				AutoGenerated: fix.AutoGenerated,
			}
			require.NoError(t, eng.CreateEdge(edge), "CreateEdge(%q)", fix.ID)
		}
		// Overwrite each edge body with the legacy non-compact form
		// so the v1→v2 migration's pre-compact decode arm runs.
		for _, fix := range edgeFixtures {
			writeV0EdgeFixture(t, eng, fix)
		}

		require.NoError(t, eng.writeSchemaVersion(0))
		require.NoError(t, eng.Close())
	}

	// Stage 2: reopen with the upgrade flag — the full chain runs.
	eng, err := NewBadgerEngineWithOptions(BadgerOptions{
		DataDir:             dir,
		AllowStorageUpgrade: true,
	})
	require.NoError(t, err)
	t.Cleanup(func() { eng.Close() })

	// Schema version landed at current.
	require.Equal(t, storageVersionCurrent, eng.storageVersion)
	v, err := eng.readSchemaVersion()
	require.NoError(t, err)
	require.Equal(t, storageVersionCurrent, v)

	// Every node body now starts with the v2 format byte.
	require.NoError(t, eng.db.View(func(txn *badger.Txn) error {
		opts := badger.DefaultIteratorOptions
		opts.Prefix = []byte{prefixNode}
		opts.PrefetchValues = true
		it := txn.NewIterator(opts)
		defer it.Close()
		seen := 0
		for it.Rewind(); it.ValidForPrefix(opts.Prefix); it.Next() {
			val, err := it.Item().ValueCopy(nil)
			require.NoError(t, err)
			require.NotEmpty(t, val)
			require.Equal(t, byte(nodeFormatTokenizedV1), val[0],
				"node %q body did not get rewritten to v2", string(it.Item().Key()[1:]))
			seen++
		}
		require.Equal(t, len(nodeFixtures), seen)
		return nil
	}))

	// Every edge body now starts with the v2 compact format byte.
	require.NoError(t, eng.db.View(func(txn *badger.Txn) error {
		opts := badger.DefaultIteratorOptions
		opts.Prefix = []byte{prefixEdge}
		opts.PrefetchValues = true
		it := txn.NewIterator(opts)
		defer it.Close()
		seen := 0
		for it.Rewind(); it.ValidForPrefix(opts.Prefix); it.Next() {
			val, err := it.Item().ValueCopy(nil)
			require.NoError(t, err)
			require.NotEmpty(t, val)
			require.Equal(t, byte(edgeFormatCompactV2), val[0],
				"edge %q body did not get rewritten to v2", string(it.Item().Key()[1:]))
			seen++
		}
		require.Equal(t, 3, seen)
		return nil
	}))

	// Round-trip every node through the public read path. Labels and
	// properties must come back exactly as we wrote them.
	for _, fix := range nodeFixtures {
		got, err := eng.GetNode(fix.ID)
		require.NoError(t, err, "GetNode(%q)", fix.ID)
		require.NotNil(t, got, "GetNode(%q) returned nil", fix.ID)

		gotLabels := append([]string(nil), got.Labels...)
		wantLabels := append([]string(nil), fix.Labels...)
		sort.Strings(gotLabels)
		sort.Strings(wantLabels)
		require.Equal(t, wantLabels, gotLabels, "labels for %q", fix.ID)

		require.Equal(t, fix.Properties, got.Properties, "properties for %q", fix.ID)
	}

	// Round-trip the edges. Endpoints, type, and properties must
	// survive verbatim.
	expectedEdges := map[EdgeID]e2eFixtureEdge{
		"team-alpha:edge-knows-1": {
			StartNode: "team-alpha:alice",
			EndNode:   "team-alpha:bob",
			Type:      "KNOWS",
			Properties: map[string]any{
				"since":    "2020-01-15",
				"strength": "close",
			},
		},
		"team-alpha:edge-mentors-1": {
			StartNode: "team-alpha:alice",
			EndNode:   "team-alpha:carol",
			Type:      "MENTORS",
			Properties: map[string]any{
				"since":    "2021-09-01",
				"sessions": int64(48),
			},
		},
		"team-alpha:edge-authored-1": {
			StartNode: "team-alpha:alice",
			EndNode:   "team-beta:doc-42",
			Type:      "AUTHORED",
			Properties: map[string]any{
				"role": "lead",
			},
		},
	}
	for id, want := range expectedEdges {
		got, err := eng.GetEdge(id)
		require.NoError(t, err, "GetEdge(%q)", id)
		require.NotNil(t, got, "GetEdge(%q) returned nil", id)
		require.Equal(t, want.StartNode, got.StartNode, "start node for %q", id)
		require.Equal(t, want.EndNode, got.EndNode, "end node for %q", id)
		require.Equal(t, want.Type, got.Type, "type for %q", id)
		require.Equal(t, want.Properties, got.Properties, "properties for %q", id)
	}

	// Label-index queries: every node should be findable by every
	// label it claims, since the migration recomputes label indexes
	// off the rewritten v2 bodies.
	labelExpect := map[string][]NodeID{
		"Person":   {"team-alpha:alice", "team-alpha:bob", "team-alpha:carol"},
		"Engineer": {"team-alpha:alice"},
		"Designer": {"team-alpha:carol"},
		"Document": {"team-beta:doc-42"},
		"Public":   {"team-beta:doc-42"},
	}
	for label, wantIDs := range labelExpect {
		nodes, err := eng.GetNodesByLabel(label)
		require.NoError(t, err, "GetNodesByLabel(%q)", label)
		gotIDs := make([]NodeID, 0, len(nodes))
		for _, n := range nodes {
			gotIDs = append(gotIDs, n.ID)
		}
		sort.Slice(gotIDs, func(i, j int) bool { return gotIDs[i] < gotIDs[j] })
		sort.Slice(wantIDs, func(i, j int) bool { return wantIDs[i] < wantIDs[j] })
		require.Equal(t, wantIDs, gotIDs, "label %q membership", label)
	}

	// Edge-type-index queries: each edge type returns the edges we
	// staged.
	for edgeType, wantID := range map[string]EdgeID{
		"KNOWS":    "team-alpha:edge-knows-1",
		"MENTORS":  "team-alpha:edge-mentors-1",
		"AUTHORED": "team-alpha:edge-authored-1",
	} {
		edges, err := eng.GetEdgesByType(edgeType)
		require.NoError(t, err, "GetEdgesByType(%q)", edgeType)
		require.Len(t, edges, 1, "edges of type %q", edgeType)
		require.Equal(t, wantID, edges[0].ID)
	}

	// Outgoing-edge traversal: alice has three outgoing edges; bob
	// and carol have none.
	aliceOut, err := eng.GetOutgoingEdges("team-alpha:alice")
	require.NoError(t, err)
	gotIDs := make([]string, 0, len(aliceOut))
	for _, e := range aliceOut {
		gotIDs = append(gotIDs, string(e.ID))
	}
	sort.Strings(gotIDs)
	require.Equal(t, []string{
		"team-alpha:edge-authored-1",
		"team-alpha:edge-knows-1",
		"team-alpha:edge-mentors-1",
	}, gotIDs)

	bobOut, err := eng.GetOutgoingEdges("team-alpha:bob")
	require.NoError(t, err)
	require.Empty(t, bobOut)

	// edges-between (uses the edge-between index, which migrations
	// rebuild via ensureEdgeBetweenIndex).
	knowsBetween, err := eng.GetEdgesBetween("team-alpha:alice", "team-alpha:bob")
	require.NoError(t, err)
	require.Len(t, knowsBetween, 1)
	require.Equal(t, EdgeID("team-alpha:edge-knows-1"), knowsBetween[0].ID)

	// Access metadata: v0→v1 lifted DecayScore/AccessCount/
	// LastAccessed onto AccessMeta records, but ONLY for nodes that
	// had non-zero access state. Carol had none — no entry expected.
	for _, fix := range nodeFixtures {
		meta, err := eng.GetAccessMeta(string(fix.ID))
		require.NoError(t, err, "GetAccessMeta(%q)", fix.ID)
		if fix.AccessCount == 0 && fix.DecayScore == 0 && fix.LastAccessed.IsZero() {
			require.Nil(t, meta, "expected no AccessMeta for %q", fix.ID)
			continue
		}
		require.NotNil(t, meta, "expected AccessMeta for %q", fix.ID)
		require.Equal(t, knowledgepolicy.ScopeNode, meta.TargetScope)
		require.Equal(t, fix.AccessCount, meta.Fixed.AccessCount, "access count for %q", fix.ID)
		require.Equal(t, fix.LastAccessed.UnixNano(), meta.Fixed.LastAccessedAt, "last-accessed for %q", fix.ID)
	}

	// Node/edge counts match the fixtures.
	nodeCount, err := eng.NodeCount()
	require.NoError(t, err)
	require.Equal(t, int64(len(nodeFixtures)), nodeCount)

	edgeCount, err := eng.EdgeCount()
	require.NoError(t, err)
	require.Equal(t, int64(3), edgeCount)
}
